package com.ejunhai.qutihuo.statistical.dao;

import com.ejunhai.qutihuo.statistical.model.Adminpermission;
import com.ejunhai.qutihuo.statistical.model.AdminpermissionExample;

import java.util.List;


public interface AdminpermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    int insert(Adminpermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    int insertSelective(Adminpermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    List<Adminpermission> selectByExample(AdminpermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    Adminpermission selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    int updateByPrimaryKeySelective(Adminpermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    int updateByPrimaryKey(Adminpermission record);
    /**
     * 获取所有包含的省份
     *
     * @return 省份数组
     */
    List<String> getDistinctProvince();

    /**
     * 获取所有包含的年份
     *
     * @return 年份数组
     */
    List<Integer> getDistinctYear();

}