package com.ejunhai.qutihuo.statistical.dao;

import com.ejunhai.qutihuo.statistical.model.Adminresponsecase;
import com.ejunhai.qutihuo.statistical.model.AdminresponsecaseExample;
import java.util.List;

public interface AdminresponsecaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    int insert(Adminresponsecase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    int insertSelective(Adminresponsecase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    List<Adminresponsecase> selectByExample(AdminresponsecaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    Adminresponsecase selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    int updateByPrimaryKeySelective(Adminresponsecase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    int updateByPrimaryKey(Adminresponsecase record);
    /**
     * 获取所有包含的省份
     *
     * @return 省份数组
     */
    List<String> getDistinctProvince();

    /**
     * 获取所有包含的年份
     *
     * @return 年份数组
     */
    List<Integer> getDistinctYear();
}