package com.ejunhai.qutihuo.statistical.dao;

import com.ejunhai.qutihuo.statistical.model.Fixedassetsandcapitalconstruction;
import com.ejunhai.qutihuo.statistical.model.FixedassetsandcapitalconstructionExample;
import java.util.List;

public interface FixedassetsandcapitalconstructionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    int insert(Fixedassetsandcapitalconstruction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    int insertSelective(Fixedassetsandcapitalconstruction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    List<Fixedassetsandcapitalconstruction> selectByExample(FixedassetsandcapitalconstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    Fixedassetsandcapitalconstruction selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    int updateByPrimaryKeySelective(Fixedassetsandcapitalconstruction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    int updateByPrimaryKey(Fixedassetsandcapitalconstruction record);
    /**
     * 获取所有包含的省份
     *
     * @return 省份数组
     */
    List<String> getDistinctProvince();

    /**
     * 获取所有包含的年份
     *
     * @return 年份数组
     */
    List<Integer> getDistinctYear();
}