package com.ejunhai.qutihuo.statistical.model;

import java.util.ArrayList;
import java.util.List;

public class AdminpermissionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public AdminpermissionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("Province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("Province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("Province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("Province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("Province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("Province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("Province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("Province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("Province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("Province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("Province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("Province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("Province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("Province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andApplyCntOrgIsNull() {
            addCriterion("Apply_cnt_org is null");
            return (Criteria) this;
        }

        public Criteria andApplyCntOrgIsNotNull() {
            addCriterion("Apply_cnt_org is not null");
            return (Criteria) this;
        }

        public Criteria andApplyCntOrgEqualTo(Integer value) {
            addCriterion("Apply_cnt_org =", value, "applyCntOrg");
            return (Criteria) this;
        }

        public Criteria andApplyCntOrgNotEqualTo(Integer value) {
            addCriterion("Apply_cnt_org <>", value, "applyCntOrg");
            return (Criteria) this;
        }

        public Criteria andApplyCntOrgGreaterThan(Integer value) {
            addCriterion("Apply_cnt_org >", value, "applyCntOrg");
            return (Criteria) this;
        }

        public Criteria andApplyCntOrgGreaterThanOrEqualTo(Integer value) {
            addCriterion("Apply_cnt_org >=", value, "applyCntOrg");
            return (Criteria) this;
        }

        public Criteria andApplyCntOrgLessThan(Integer value) {
            addCriterion("Apply_cnt_org <", value, "applyCntOrg");
            return (Criteria) this;
        }

        public Criteria andApplyCntOrgLessThanOrEqualTo(Integer value) {
            addCriterion("Apply_cnt_org <=", value, "applyCntOrg");
            return (Criteria) this;
        }

        public Criteria andApplyCntOrgIn(List<Integer> values) {
            addCriterion("Apply_cnt_org in", values, "applyCntOrg");
            return (Criteria) this;
        }

        public Criteria andApplyCntOrgNotIn(List<Integer> values) {
            addCriterion("Apply_cnt_org not in", values, "applyCntOrg");
            return (Criteria) this;
        }

        public Criteria andApplyCntOrgBetween(Integer value1, Integer value2) {
            addCriterion("Apply_cnt_org between", value1, value2, "applyCntOrg");
            return (Criteria) this;
        }

        public Criteria andApplyCntOrgNotBetween(Integer value1, Integer value2) {
            addCriterion("Apply_cnt_org not between", value1, value2, "applyCntOrg");
            return (Criteria) this;
        }

        public Criteria andApplyCntPersonIsNull() {
            addCriterion("Apply_cnt_person is null");
            return (Criteria) this;
        }

        public Criteria andApplyCntPersonIsNotNull() {
            addCriterion("Apply_cnt_person is not null");
            return (Criteria) this;
        }

        public Criteria andApplyCntPersonEqualTo(Integer value) {
            addCriterion("Apply_cnt_person =", value, "applyCntPerson");
            return (Criteria) this;
        }

        public Criteria andApplyCntPersonNotEqualTo(Integer value) {
            addCriterion("Apply_cnt_person <>", value, "applyCntPerson");
            return (Criteria) this;
        }

        public Criteria andApplyCntPersonGreaterThan(Integer value) {
            addCriterion("Apply_cnt_person >", value, "applyCntPerson");
            return (Criteria) this;
        }

        public Criteria andApplyCntPersonGreaterThanOrEqualTo(Integer value) {
            addCriterion("Apply_cnt_person >=", value, "applyCntPerson");
            return (Criteria) this;
        }

        public Criteria andApplyCntPersonLessThan(Integer value) {
            addCriterion("Apply_cnt_person <", value, "applyCntPerson");
            return (Criteria) this;
        }

        public Criteria andApplyCntPersonLessThanOrEqualTo(Integer value) {
            addCriterion("Apply_cnt_person <=", value, "applyCntPerson");
            return (Criteria) this;
        }

        public Criteria andApplyCntPersonIn(List<Integer> values) {
            addCriterion("Apply_cnt_person in", values, "applyCntPerson");
            return (Criteria) this;
        }

        public Criteria andApplyCntPersonNotIn(List<Integer> values) {
            addCriterion("Apply_cnt_person not in", values, "applyCntPerson");
            return (Criteria) this;
        }

        public Criteria andApplyCntPersonBetween(Integer value1, Integer value2) {
            addCriterion("Apply_cnt_person between", value1, value2, "applyCntPerson");
            return (Criteria) this;
        }

        public Criteria andApplyCntPersonNotBetween(Integer value1, Integer value2) {
            addCriterion("Apply_cnt_person not between", value1, value2, "applyCntPerson");
            return (Criteria) this;
        }

        public Criteria andApplyAccIsNull() {
            addCriterion("Apply_ACC is null");
            return (Criteria) this;
        }

        public Criteria andApplyAccIsNotNull() {
            addCriterion("Apply_ACC is not null");
            return (Criteria) this;
        }

        public Criteria andApplyAccEqualTo(Integer value) {
            addCriterion("Apply_ACC =", value, "applyAcc");
            return (Criteria) this;
        }

        public Criteria andApplyAccNotEqualTo(Integer value) {
            addCriterion("Apply_ACC <>", value, "applyAcc");
            return (Criteria) this;
        }

        public Criteria andApplyAccGreaterThan(Integer value) {
            addCriterion("Apply_ACC >", value, "applyAcc");
            return (Criteria) this;
        }

        public Criteria andApplyAccGreaterThanOrEqualTo(Integer value) {
            addCriterion("Apply_ACC >=", value, "applyAcc");
            return (Criteria) this;
        }

        public Criteria andApplyAccLessThan(Integer value) {
            addCriterion("Apply_ACC <", value, "applyAcc");
            return (Criteria) this;
        }

        public Criteria andApplyAccLessThanOrEqualTo(Integer value) {
            addCriterion("Apply_ACC <=", value, "applyAcc");
            return (Criteria) this;
        }

        public Criteria andApplyAccIn(List<Integer> values) {
            addCriterion("Apply_ACC in", values, "applyAcc");
            return (Criteria) this;
        }

        public Criteria andApplyAccNotIn(List<Integer> values) {
            addCriterion("Apply_ACC not in", values, "applyAcc");
            return (Criteria) this;
        }

        public Criteria andApplyAccBetween(Integer value1, Integer value2) {
            addCriterion("Apply_ACC between", value1, value2, "applyAcc");
            return (Criteria) this;
        }

        public Criteria andApplyAccNotBetween(Integer value1, Integer value2) {
            addCriterion("Apply_ACC not between", value1, value2, "applyAcc");
            return (Criteria) this;
        }

        public Criteria andApplyRegIsNull() {
            addCriterion("Apply_REG is null");
            return (Criteria) this;
        }

        public Criteria andApplyRegIsNotNull() {
            addCriterion("Apply_REG is not null");
            return (Criteria) this;
        }

        public Criteria andApplyRegEqualTo(Integer value) {
            addCriterion("Apply_REG =", value, "applyReg");
            return (Criteria) this;
        }

        public Criteria andApplyRegNotEqualTo(Integer value) {
            addCriterion("Apply_REG <>", value, "applyReg");
            return (Criteria) this;
        }

        public Criteria andApplyRegGreaterThan(Integer value) {
            addCriterion("Apply_REG >", value, "applyReg");
            return (Criteria) this;
        }

        public Criteria andApplyRegGreaterThanOrEqualTo(Integer value) {
            addCriterion("Apply_REG >=", value, "applyReg");
            return (Criteria) this;
        }

        public Criteria andApplyRegLessThan(Integer value) {
            addCriterion("Apply_REG <", value, "applyReg");
            return (Criteria) this;
        }

        public Criteria andApplyRegLessThanOrEqualTo(Integer value) {
            addCriterion("Apply_REG <=", value, "applyReg");
            return (Criteria) this;
        }

        public Criteria andApplyRegIn(List<Integer> values) {
            addCriterion("Apply_REG in", values, "applyReg");
            return (Criteria) this;
        }

        public Criteria andApplyRegNotIn(List<Integer> values) {
            addCriterion("Apply_REG not in", values, "applyReg");
            return (Criteria) this;
        }

        public Criteria andApplyRegBetween(Integer value1, Integer value2) {
            addCriterion("Apply_REG between", value1, value2, "applyReg");
            return (Criteria) this;
        }

        public Criteria andApplyRegNotBetween(Integer value1, Integer value2) {
            addCriterion("Apply_REG not between", value1, value2, "applyReg");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditAccIsNull() {
            addCriterion("Permission_Audit_ACC is null");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditAccIsNotNull() {
            addCriterion("Permission_Audit_ACC is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditAccEqualTo(Integer value) {
            addCriterion("Permission_Audit_ACC =", value, "permissionAuditAcc");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditAccNotEqualTo(Integer value) {
            addCriterion("Permission_Audit_ACC <>", value, "permissionAuditAcc");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditAccGreaterThan(Integer value) {
            addCriterion("Permission_Audit_ACC >", value, "permissionAuditAcc");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditAccGreaterThanOrEqualTo(Integer value) {
            addCriterion("Permission_Audit_ACC >=", value, "permissionAuditAcc");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditAccLessThan(Integer value) {
            addCriterion("Permission_Audit_ACC <", value, "permissionAuditAcc");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditAccLessThanOrEqualTo(Integer value) {
            addCriterion("Permission_Audit_ACC <=", value, "permissionAuditAcc");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditAccIn(List<Integer> values) {
            addCriterion("Permission_Audit_ACC in", values, "permissionAuditAcc");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditAccNotIn(List<Integer> values) {
            addCriterion("Permission_Audit_ACC not in", values, "permissionAuditAcc");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditAccBetween(Integer value1, Integer value2) {
            addCriterion("Permission_Audit_ACC between", value1, value2, "permissionAuditAcc");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditAccNotBetween(Integer value1, Integer value2) {
            addCriterion("Permission_Audit_ACC not between", value1, value2, "permissionAuditAcc");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditRejIsNull() {
            addCriterion("Permission_Audit_REJ is null");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditRejIsNotNull() {
            addCriterion("Permission_Audit_REJ is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditRejEqualTo(Integer value) {
            addCriterion("Permission_Audit_REJ =", value, "permissionAuditRej");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditRejNotEqualTo(Integer value) {
            addCriterion("Permission_Audit_REJ <>", value, "permissionAuditRej");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditRejGreaterThan(Integer value) {
            addCriterion("Permission_Audit_REJ >", value, "permissionAuditRej");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditRejGreaterThanOrEqualTo(Integer value) {
            addCriterion("Permission_Audit_REJ >=", value, "permissionAuditRej");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditRejLessThan(Integer value) {
            addCriterion("Permission_Audit_REJ <", value, "permissionAuditRej");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditRejLessThanOrEqualTo(Integer value) {
            addCriterion("Permission_Audit_REJ <=", value, "permissionAuditRej");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditRejIn(List<Integer> values) {
            addCriterion("Permission_Audit_REJ in", values, "permissionAuditRej");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditRejNotIn(List<Integer> values) {
            addCriterion("Permission_Audit_REJ not in", values, "permissionAuditRej");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditRejBetween(Integer value1, Integer value2) {
            addCriterion("Permission_Audit_REJ between", value1, value2, "permissionAuditRej");
            return (Criteria) this;
        }

        public Criteria andPermissionAuditRejNotBetween(Integer value1, Integer value2) {
            addCriterion("Permission_Audit_REJ not between", value1, value2, "permissionAuditRej");
            return (Criteria) this;
        }

        public Criteria andModifyIsNull() {
            addCriterion("Modify is null");
            return (Criteria) this;
        }

        public Criteria andModifyIsNotNull() {
            addCriterion("Modify is not null");
            return (Criteria) this;
        }

        public Criteria andModifyEqualTo(Integer value) {
            addCriterion("Modify =", value, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyNotEqualTo(Integer value) {
            addCriterion("Modify <>", value, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyGreaterThan(Integer value) {
            addCriterion("Modify >", value, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyGreaterThanOrEqualTo(Integer value) {
            addCriterion("Modify >=", value, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyLessThan(Integer value) {
            addCriterion("Modify <", value, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyLessThanOrEqualTo(Integer value) {
            addCriterion("Modify <=", value, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyIn(List<Integer> values) {
            addCriterion("Modify in", values, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyNotIn(List<Integer> values) {
            addCriterion("Modify not in", values, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyBetween(Integer value1, Integer value2) {
            addCriterion("Modify between", value1, value2, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyNotBetween(Integer value1, Integer value2) {
            addCriterion("Modify not between", value1, value2, "modify");
            return (Criteria) this;
        }

        public Criteria andDelayIsNull() {
            addCriterion("Delay is null");
            return (Criteria) this;
        }

        public Criteria andDelayIsNotNull() {
            addCriterion("Delay is not null");
            return (Criteria) this;
        }

        public Criteria andDelayEqualTo(Integer value) {
            addCriterion("Delay =", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayNotEqualTo(Integer value) {
            addCriterion("Delay <>", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayGreaterThan(Integer value) {
            addCriterion("Delay >", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayGreaterThanOrEqualTo(Integer value) {
            addCriterion("Delay >=", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayLessThan(Integer value) {
            addCriterion("Delay <", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayLessThanOrEqualTo(Integer value) {
            addCriterion("Delay <=", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayIn(List<Integer> values) {
            addCriterion("Delay in", values, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayNotIn(List<Integer> values) {
            addCriterion("Delay not in", values, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayBetween(Integer value1, Integer value2) {
            addCriterion("Delay between", value1, value2, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayNotBetween(Integer value1, Integer value2) {
            addCriterion("Delay not between", value1, value2, "delay");
            return (Criteria) this;
        }

        public Criteria andPermissionBackIsNull() {
            addCriterion("Permission_Back is null");
            return (Criteria) this;
        }

        public Criteria andPermissionBackIsNotNull() {
            addCriterion("Permission_Back is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionBackEqualTo(Integer value) {
            addCriterion("Permission_Back =", value, "permissionBack");
            return (Criteria) this;
        }

        public Criteria andPermissionBackNotEqualTo(Integer value) {
            addCriterion("Permission_Back <>", value, "permissionBack");
            return (Criteria) this;
        }

        public Criteria andPermissionBackGreaterThan(Integer value) {
            addCriterion("Permission_Back >", value, "permissionBack");
            return (Criteria) this;
        }

        public Criteria andPermissionBackGreaterThanOrEqualTo(Integer value) {
            addCriterion("Permission_Back >=", value, "permissionBack");
            return (Criteria) this;
        }

        public Criteria andPermissionBackLessThan(Integer value) {
            addCriterion("Permission_Back <", value, "permissionBack");
            return (Criteria) this;
        }

        public Criteria andPermissionBackLessThanOrEqualTo(Integer value) {
            addCriterion("Permission_Back <=", value, "permissionBack");
            return (Criteria) this;
        }

        public Criteria andPermissionBackIn(List<Integer> values) {
            addCriterion("Permission_Back in", values, "permissionBack");
            return (Criteria) this;
        }

        public Criteria andPermissionBackNotIn(List<Integer> values) {
            addCriterion("Permission_Back not in", values, "permissionBack");
            return (Criteria) this;
        }

        public Criteria andPermissionBackBetween(Integer value1, Integer value2) {
            addCriterion("Permission_Back between", value1, value2, "permissionBack");
            return (Criteria) this;
        }

        public Criteria andPermissionBackNotBetween(Integer value1, Integer value2) {
            addCriterion("Permission_Back not between", value1, value2, "permissionBack");
            return (Criteria) this;
        }

        public Criteria andPermissionRevocationIsNull() {
            addCriterion("Permission_Revocation is null");
            return (Criteria) this;
        }

        public Criteria andPermissionRevocationIsNotNull() {
            addCriterion("Permission_Revocation is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionRevocationEqualTo(Integer value) {
            addCriterion("Permission_Revocation =", value, "permissionRevocation");
            return (Criteria) this;
        }

        public Criteria andPermissionRevocationNotEqualTo(Integer value) {
            addCriterion("Permission_Revocation <>", value, "permissionRevocation");
            return (Criteria) this;
        }

        public Criteria andPermissionRevocationGreaterThan(Integer value) {
            addCriterion("Permission_Revocation >", value, "permissionRevocation");
            return (Criteria) this;
        }

        public Criteria andPermissionRevocationGreaterThanOrEqualTo(Integer value) {
            addCriterion("Permission_Revocation >=", value, "permissionRevocation");
            return (Criteria) this;
        }

        public Criteria andPermissionRevocationLessThan(Integer value) {
            addCriterion("Permission_Revocation <", value, "permissionRevocation");
            return (Criteria) this;
        }

        public Criteria andPermissionRevocationLessThanOrEqualTo(Integer value) {
            addCriterion("Permission_Revocation <=", value, "permissionRevocation");
            return (Criteria) this;
        }

        public Criteria andPermissionRevocationIn(List<Integer> values) {
            addCriterion("Permission_Revocation in", values, "permissionRevocation");
            return (Criteria) this;
        }

        public Criteria andPermissionRevocationNotIn(List<Integer> values) {
            addCriterion("Permission_Revocation not in", values, "permissionRevocation");
            return (Criteria) this;
        }

        public Criteria andPermissionRevocationBetween(Integer value1, Integer value2) {
            addCriterion("Permission_Revocation between", value1, value2, "permissionRevocation");
            return (Criteria) this;
        }

        public Criteria andPermissionRevocationNotBetween(Integer value1, Integer value2) {
            addCriterion("Permission_Revocation not between", value1, value2, "permissionRevocation");
            return (Criteria) this;
        }

        public Criteria andPermissionDeactiveIsNull() {
            addCriterion("Permission_Deactive is null");
            return (Criteria) this;
        }

        public Criteria andPermissionDeactiveIsNotNull() {
            addCriterion("Permission_Deactive is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionDeactiveEqualTo(Integer value) {
            addCriterion("Permission_Deactive =", value, "permissionDeactive");
            return (Criteria) this;
        }

        public Criteria andPermissionDeactiveNotEqualTo(Integer value) {
            addCriterion("Permission_Deactive <>", value, "permissionDeactive");
            return (Criteria) this;
        }

        public Criteria andPermissionDeactiveGreaterThan(Integer value) {
            addCriterion("Permission_Deactive >", value, "permissionDeactive");
            return (Criteria) this;
        }

        public Criteria andPermissionDeactiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("Permission_Deactive >=", value, "permissionDeactive");
            return (Criteria) this;
        }

        public Criteria andPermissionDeactiveLessThan(Integer value) {
            addCriterion("Permission_Deactive <", value, "permissionDeactive");
            return (Criteria) this;
        }

        public Criteria andPermissionDeactiveLessThanOrEqualTo(Integer value) {
            addCriterion("Permission_Deactive <=", value, "permissionDeactive");
            return (Criteria) this;
        }

        public Criteria andPermissionDeactiveIn(List<Integer> values) {
            addCriterion("Permission_Deactive in", values, "permissionDeactive");
            return (Criteria) this;
        }

        public Criteria andPermissionDeactiveNotIn(List<Integer> values) {
            addCriterion("Permission_Deactive not in", values, "permissionDeactive");
            return (Criteria) this;
        }

        public Criteria andPermissionDeactiveBetween(Integer value1, Integer value2) {
            addCriterion("Permission_Deactive between", value1, value2, "permissionDeactive");
            return (Criteria) this;
        }

        public Criteria andPermissionDeactiveNotBetween(Integer value1, Integer value2) {
            addCriterion("Permission_Deactive not between", value1, value2, "permissionDeactive");
            return (Criteria) this;
        }

        public Criteria andPermissionCancelIsNull() {
            addCriterion("Permission_Cancel is null");
            return (Criteria) this;
        }

        public Criteria andPermissionCancelIsNotNull() {
            addCriterion("Permission_Cancel is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionCancelEqualTo(Integer value) {
            addCriterion("Permission_Cancel =", value, "permissionCancel");
            return (Criteria) this;
        }

        public Criteria andPermissionCancelNotEqualTo(Integer value) {
            addCriterion("Permission_Cancel <>", value, "permissionCancel");
            return (Criteria) this;
        }

        public Criteria andPermissionCancelGreaterThan(Integer value) {
            addCriterion("Permission_Cancel >", value, "permissionCancel");
            return (Criteria) this;
        }

        public Criteria andPermissionCancelGreaterThanOrEqualTo(Integer value) {
            addCriterion("Permission_Cancel >=", value, "permissionCancel");
            return (Criteria) this;
        }

        public Criteria andPermissionCancelLessThan(Integer value) {
            addCriterion("Permission_Cancel <", value, "permissionCancel");
            return (Criteria) this;
        }

        public Criteria andPermissionCancelLessThanOrEqualTo(Integer value) {
            addCriterion("Permission_Cancel <=", value, "permissionCancel");
            return (Criteria) this;
        }

        public Criteria andPermissionCancelIn(List<Integer> values) {
            addCriterion("Permission_Cancel in", values, "permissionCancel");
            return (Criteria) this;
        }

        public Criteria andPermissionCancelNotIn(List<Integer> values) {
            addCriterion("Permission_Cancel not in", values, "permissionCancel");
            return (Criteria) this;
        }

        public Criteria andPermissionCancelBetween(Integer value1, Integer value2) {
            addCriterion("Permission_Cancel between", value1, value2, "permissionCancel");
            return (Criteria) this;
        }

        public Criteria andPermissionCancelNotBetween(Integer value1, Integer value2) {
            addCriterion("Permission_Cancel not between", value1, value2, "permissionCancel");
            return (Criteria) this;
        }

        public Criteria andPermissionIncomeIsNull() {
            addCriterion("Permission_Income is null");
            return (Criteria) this;
        }

        public Criteria andPermissionIncomeIsNotNull() {
            addCriterion("Permission_Income is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionIncomeEqualTo(Integer value) {
            addCriterion("Permission_Income =", value, "permissionIncome");
            return (Criteria) this;
        }

        public Criteria andPermissionIncomeNotEqualTo(Integer value) {
            addCriterion("Permission_Income <>", value, "permissionIncome");
            return (Criteria) this;
        }

        public Criteria andPermissionIncomeGreaterThan(Integer value) {
            addCriterion("Permission_Income >", value, "permissionIncome");
            return (Criteria) this;
        }

        public Criteria andPermissionIncomeGreaterThanOrEqualTo(Integer value) {
            addCriterion("Permission_Income >=", value, "permissionIncome");
            return (Criteria) this;
        }

        public Criteria andPermissionIncomeLessThan(Integer value) {
            addCriterion("Permission_Income <", value, "permissionIncome");
            return (Criteria) this;
        }

        public Criteria andPermissionIncomeLessThanOrEqualTo(Integer value) {
            addCriterion("Permission_Income <=", value, "permissionIncome");
            return (Criteria) this;
        }

        public Criteria andPermissionIncomeIn(List<Integer> values) {
            addCriterion("Permission_Income in", values, "permissionIncome");
            return (Criteria) this;
        }

        public Criteria andPermissionIncomeNotIn(List<Integer> values) {
            addCriterion("Permission_Income not in", values, "permissionIncome");
            return (Criteria) this;
        }

        public Criteria andPermissionIncomeBetween(Integer value1, Integer value2) {
            addCriterion("Permission_Income between", value1, value2, "permissionIncome");
            return (Criteria) this;
        }

        public Criteria andPermissionIncomeNotBetween(Integer value1, Integer value2) {
            addCriterion("Permission_Income not between", value1, value2, "permissionIncome");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(Integer value) {
            addCriterion("year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(Integer value) {
            addCriterion("year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(Integer value) {
            addCriterion("year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(Integer value) {
            addCriterion("year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(Integer value) {
            addCriterion("year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<Integer> values) {
            addCriterion("year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<Integer> values) {
            addCriterion("year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(Integer value1, Integer value2) {
            addCriterion("year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(Integer value1, Integer value2) {
            addCriterion("year not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andSeqnoIsNull() {
            addCriterion("seqno is null");
            return (Criteria) this;
        }

        public Criteria andSeqnoIsNotNull() {
            addCriterion("seqno is not null");
            return (Criteria) this;
        }

        public Criteria andSeqnoEqualTo(Integer value) {
            addCriterion("seqno =", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotEqualTo(Integer value) {
            addCriterion("seqno <>", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoGreaterThan(Integer value) {
            addCriterion("seqno >", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("seqno >=", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLessThan(Integer value) {
            addCriterion("seqno <", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLessThanOrEqualTo(Integer value) {
            addCriterion("seqno <=", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoIn(List<Integer> values) {
            addCriterion("seqno in", values, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotIn(List<Integer> values) {
            addCriterion("seqno not in", values, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoBetween(Integer value1, Integer value2) {
            addCriterion("seqno between", value1, value2, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotBetween(Integer value1, Integer value2) {
            addCriterion("seqno not between", value1, value2, "seqno");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adminpermission
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 11 20:06:36 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adminpermission
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}