package com.ejunhai.qutihuo.statistical.model;

public class Adminpermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.ID
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.Province
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.Apply_cnt_org
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer applyCntOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.Apply_cnt_person
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer applyCntPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.Apply_ACC
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer applyAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.Apply_REG
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer applyReg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.Permission_Audit_ACC
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer permissionAuditAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.Permission_Audit_REJ
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer permissionAuditRej;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.Modify
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer modify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.Delay
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer delay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.Permission_Back
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer permissionBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.Permission_Revocation
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer permissionRevocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.Permission_Deactive
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer permissionDeactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.Permission_Cancel
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer permissionCancel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.Permission_Income
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer permissionIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.year
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminpermission.seqno
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    private Integer seqno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.ID
     *
     * @return the value of adminpermission.ID
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.ID
     *
     * @param id the value for adminpermission.ID
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.Province
     *
     * @return the value of adminpermission.Province
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.Province
     *
     * @param province the value for adminpermission.Province
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.Apply_cnt_org
     *
     * @return the value of adminpermission.Apply_cnt_org
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getApplyCntOrg() {
        return applyCntOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.Apply_cnt_org
     *
     * @param applyCntOrg the value for adminpermission.Apply_cnt_org
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setApplyCntOrg(Integer applyCntOrg) {
        this.applyCntOrg = applyCntOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.Apply_cnt_person
     *
     * @return the value of adminpermission.Apply_cnt_person
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getApplyCntPerson() {
        return applyCntPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.Apply_cnt_person
     *
     * @param applyCntPerson the value for adminpermission.Apply_cnt_person
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setApplyCntPerson(Integer applyCntPerson) {
        this.applyCntPerson = applyCntPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.Apply_ACC
     *
     * @return the value of adminpermission.Apply_ACC
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getApplyAcc() {
        return applyAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.Apply_ACC
     *
     * @param applyAcc the value for adminpermission.Apply_ACC
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setApplyAcc(Integer applyAcc) {
        this.applyAcc = applyAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.Apply_REG
     *
     * @return the value of adminpermission.Apply_REG
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getApplyReg() {
        return applyReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.Apply_REG
     *
     * @param applyReg the value for adminpermission.Apply_REG
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setApplyReg(Integer applyReg) {
        this.applyReg = applyReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.Permission_Audit_ACC
     *
     * @return the value of adminpermission.Permission_Audit_ACC
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getPermissionAuditAcc() {
        return permissionAuditAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.Permission_Audit_ACC
     *
     * @param permissionAuditAcc the value for adminpermission.Permission_Audit_ACC
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setPermissionAuditAcc(Integer permissionAuditAcc) {
        this.permissionAuditAcc = permissionAuditAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.Permission_Audit_REJ
     *
     * @return the value of adminpermission.Permission_Audit_REJ
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getPermissionAuditRej() {
        return permissionAuditRej;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.Permission_Audit_REJ
     *
     * @param permissionAuditRej the value for adminpermission.Permission_Audit_REJ
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setPermissionAuditRej(Integer permissionAuditRej) {
        this.permissionAuditRej = permissionAuditRej;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.Modify
     *
     * @return the value of adminpermission.Modify
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getModify() {
        return modify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.Modify
     *
     * @param modify the value for adminpermission.Modify
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setModify(Integer modify) {
        this.modify = modify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.Delay
     *
     * @return the value of adminpermission.Delay
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getDelay() {
        return delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.Delay
     *
     * @param delay the value for adminpermission.Delay
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setDelay(Integer delay) {
        this.delay = delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.Permission_Back
     *
     * @return the value of adminpermission.Permission_Back
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getPermissionBack() {
        return permissionBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.Permission_Back
     *
     * @param permissionBack the value for adminpermission.Permission_Back
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setPermissionBack(Integer permissionBack) {
        this.permissionBack = permissionBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.Permission_Revocation
     *
     * @return the value of adminpermission.Permission_Revocation
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getPermissionRevocation() {
        return permissionRevocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.Permission_Revocation
     *
     * @param permissionRevocation the value for adminpermission.Permission_Revocation
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setPermissionRevocation(Integer permissionRevocation) {
        this.permissionRevocation = permissionRevocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.Permission_Deactive
     *
     * @return the value of adminpermission.Permission_Deactive
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getPermissionDeactive() {
        return permissionDeactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.Permission_Deactive
     *
     * @param permissionDeactive the value for adminpermission.Permission_Deactive
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setPermissionDeactive(Integer permissionDeactive) {
        this.permissionDeactive = permissionDeactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.Permission_Cancel
     *
     * @return the value of adminpermission.Permission_Cancel
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getPermissionCancel() {
        return permissionCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.Permission_Cancel
     *
     * @param permissionCancel the value for adminpermission.Permission_Cancel
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setPermissionCancel(Integer permissionCancel) {
        this.permissionCancel = permissionCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.Permission_Income
     *
     * @return the value of adminpermission.Permission_Income
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getPermissionIncome() {
        return permissionIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.Permission_Income
     *
     * @param permissionIncome the value for adminpermission.Permission_Income
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setPermissionIncome(Integer permissionIncome) {
        this.permissionIncome = permissionIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.year
     *
     * @return the value of adminpermission.year
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.year
     *
     * @param year the value for adminpermission.year
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminpermission.seqno
     *
     * @return the value of adminpermission.seqno
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public Integer getSeqno() {
        return seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminpermission.seqno
     *
     * @param seqno the value for adminpermission.seqno
     *
     * @mbggenerated Wed Jul 11 20:06:36 CST 2018
     */
    public void setSeqno(Integer seqno) {
        this.seqno = seqno;
    }
}