package com.ejunhai.qutihuo.statistical.model;

public class Adminresponsecase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.ID
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.SQJZ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer sqjz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.BQFS_FYHYS
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer bqfsFyhys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.BQFS_WJFYZJYS
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer bqfsWjfyzjys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.YSJG_YJTXZXWJG
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer ysjgYjtxzxwjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.YSJG_FYJG
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer ysjgFyjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.YSJG_XZZF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer ysjgXzzf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.YSJGJB_XJBM
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer ysjgjbXjbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.YSJGJB_XJZF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer ysjgjbXjzf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.YSJGJB_DJBM
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer ysjgjbDjbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.YSJGJB_DJZF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer ysjgjbDjzf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.YSJGJB_SJBM
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer ysjgjbSjbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.YSJGJB_SJZF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer ysjgjbSjzf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.YSJGJB_QT
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer ysjgjbQt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.PJ_WC
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer pjWc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.PJ_CX_QB
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer pjCxQb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.PJ_CX_BF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer pjCxBf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.PJ_CX_CX
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer pjCxCx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.PJ_BG
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer pjBg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.PJ_LXFDZZ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer pjLxfdzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.PJ_QRHF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer pjQrhf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.PJ_QRWF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer pjQrwf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.PJ_BH
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer pjBh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.PJ_PC
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer pjPc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.PJ_BYPC
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer pjBypc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.CD_BH
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer cdBh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.CD_CS_ZD
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer cdCsZd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.CD_CS_GB
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer cdCsGb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.CD_YS
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer cdYs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.CD_ZJ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer cdZj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.CD_QT
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer cdQt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.YSJA_PCTJ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer ysjaPctj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.WSJ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer wsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.Province
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.Year
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminresponsecase.SeqNo
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    private Integer seqno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.ID
     *
     * @return the value of adminresponsecase.ID
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.ID
     *
     * @param id the value for adminresponsecase.ID
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.SQJZ
     *
     * @return the value of adminresponsecase.SQJZ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getSqjz() {
        return sqjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.SQJZ
     *
     * @param sqjz the value for adminresponsecase.SQJZ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setSqjz(Integer sqjz) {
        this.sqjz = sqjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.BQFS_FYHYS
     *
     * @return the value of adminresponsecase.BQFS_FYHYS
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getBqfsFyhys() {
        return bqfsFyhys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.BQFS_FYHYS
     *
     * @param bqfsFyhys the value for adminresponsecase.BQFS_FYHYS
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setBqfsFyhys(Integer bqfsFyhys) {
        this.bqfsFyhys = bqfsFyhys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.BQFS_WJFYZJYS
     *
     * @return the value of adminresponsecase.BQFS_WJFYZJYS
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getBqfsWjfyzjys() {
        return bqfsWjfyzjys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.BQFS_WJFYZJYS
     *
     * @param bqfsWjfyzjys the value for adminresponsecase.BQFS_WJFYZJYS
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setBqfsWjfyzjys(Integer bqfsWjfyzjys) {
        this.bqfsWjfyzjys = bqfsWjfyzjys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.YSJG_YJTXZXWJG
     *
     * @return the value of adminresponsecase.YSJG_YJTXZXWJG
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getYsjgYjtxzxwjg() {
        return ysjgYjtxzxwjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.YSJG_YJTXZXWJG
     *
     * @param ysjgYjtxzxwjg the value for adminresponsecase.YSJG_YJTXZXWJG
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setYsjgYjtxzxwjg(Integer ysjgYjtxzxwjg) {
        this.ysjgYjtxzxwjg = ysjgYjtxzxwjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.YSJG_FYJG
     *
     * @return the value of adminresponsecase.YSJG_FYJG
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getYsjgFyjg() {
        return ysjgFyjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.YSJG_FYJG
     *
     * @param ysjgFyjg the value for adminresponsecase.YSJG_FYJG
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setYsjgFyjg(Integer ysjgFyjg) {
        this.ysjgFyjg = ysjgFyjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.YSJG_XZZF
     *
     * @return the value of adminresponsecase.YSJG_XZZF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getYsjgXzzf() {
        return ysjgXzzf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.YSJG_XZZF
     *
     * @param ysjgXzzf the value for adminresponsecase.YSJG_XZZF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setYsjgXzzf(Integer ysjgXzzf) {
        this.ysjgXzzf = ysjgXzzf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.YSJGJB_XJBM
     *
     * @return the value of adminresponsecase.YSJGJB_XJBM
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getYsjgjbXjbm() {
        return ysjgjbXjbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.YSJGJB_XJBM
     *
     * @param ysjgjbXjbm the value for adminresponsecase.YSJGJB_XJBM
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setYsjgjbXjbm(Integer ysjgjbXjbm) {
        this.ysjgjbXjbm = ysjgjbXjbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.YSJGJB_XJZF
     *
     * @return the value of adminresponsecase.YSJGJB_XJZF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getYsjgjbXjzf() {
        return ysjgjbXjzf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.YSJGJB_XJZF
     *
     * @param ysjgjbXjzf the value for adminresponsecase.YSJGJB_XJZF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setYsjgjbXjzf(Integer ysjgjbXjzf) {
        this.ysjgjbXjzf = ysjgjbXjzf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.YSJGJB_DJBM
     *
     * @return the value of adminresponsecase.YSJGJB_DJBM
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getYsjgjbDjbm() {
        return ysjgjbDjbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.YSJGJB_DJBM
     *
     * @param ysjgjbDjbm the value for adminresponsecase.YSJGJB_DJBM
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setYsjgjbDjbm(Integer ysjgjbDjbm) {
        this.ysjgjbDjbm = ysjgjbDjbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.YSJGJB_DJZF
     *
     * @return the value of adminresponsecase.YSJGJB_DJZF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getYsjgjbDjzf() {
        return ysjgjbDjzf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.YSJGJB_DJZF
     *
     * @param ysjgjbDjzf the value for adminresponsecase.YSJGJB_DJZF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setYsjgjbDjzf(Integer ysjgjbDjzf) {
        this.ysjgjbDjzf = ysjgjbDjzf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.YSJGJB_SJBM
     *
     * @return the value of adminresponsecase.YSJGJB_SJBM
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getYsjgjbSjbm() {
        return ysjgjbSjbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.YSJGJB_SJBM
     *
     * @param ysjgjbSjbm the value for adminresponsecase.YSJGJB_SJBM
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setYsjgjbSjbm(Integer ysjgjbSjbm) {
        this.ysjgjbSjbm = ysjgjbSjbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.YSJGJB_SJZF
     *
     * @return the value of adminresponsecase.YSJGJB_SJZF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getYsjgjbSjzf() {
        return ysjgjbSjzf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.YSJGJB_SJZF
     *
     * @param ysjgjbSjzf the value for adminresponsecase.YSJGJB_SJZF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setYsjgjbSjzf(Integer ysjgjbSjzf) {
        this.ysjgjbSjzf = ysjgjbSjzf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.YSJGJB_QT
     *
     * @return the value of adminresponsecase.YSJGJB_QT
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getYsjgjbQt() {
        return ysjgjbQt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.YSJGJB_QT
     *
     * @param ysjgjbQt the value for adminresponsecase.YSJGJB_QT
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setYsjgjbQt(Integer ysjgjbQt) {
        this.ysjgjbQt = ysjgjbQt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.PJ_WC
     *
     * @return the value of adminresponsecase.PJ_WC
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getPjWc() {
        return pjWc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.PJ_WC
     *
     * @param pjWc the value for adminresponsecase.PJ_WC
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setPjWc(Integer pjWc) {
        this.pjWc = pjWc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.PJ_CX_QB
     *
     * @return the value of adminresponsecase.PJ_CX_QB
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getPjCxQb() {
        return pjCxQb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.PJ_CX_QB
     *
     * @param pjCxQb the value for adminresponsecase.PJ_CX_QB
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setPjCxQb(Integer pjCxQb) {
        this.pjCxQb = pjCxQb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.PJ_CX_BF
     *
     * @return the value of adminresponsecase.PJ_CX_BF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getPjCxBf() {
        return pjCxBf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.PJ_CX_BF
     *
     * @param pjCxBf the value for adminresponsecase.PJ_CX_BF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setPjCxBf(Integer pjCxBf) {
        this.pjCxBf = pjCxBf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.PJ_CX_CX
     *
     * @return the value of adminresponsecase.PJ_CX_CX
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getPjCxCx() {
        return pjCxCx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.PJ_CX_CX
     *
     * @param pjCxCx the value for adminresponsecase.PJ_CX_CX
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setPjCxCx(Integer pjCxCx) {
        this.pjCxCx = pjCxCx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.PJ_BG
     *
     * @return the value of adminresponsecase.PJ_BG
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getPjBg() {
        return pjBg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.PJ_BG
     *
     * @param pjBg the value for adminresponsecase.PJ_BG
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setPjBg(Integer pjBg) {
        this.pjBg = pjBg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.PJ_LXFDZZ
     *
     * @return the value of adminresponsecase.PJ_LXFDZZ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getPjLxfdzz() {
        return pjLxfdzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.PJ_LXFDZZ
     *
     * @param pjLxfdzz the value for adminresponsecase.PJ_LXFDZZ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setPjLxfdzz(Integer pjLxfdzz) {
        this.pjLxfdzz = pjLxfdzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.PJ_QRHF
     *
     * @return the value of adminresponsecase.PJ_QRHF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getPjQrhf() {
        return pjQrhf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.PJ_QRHF
     *
     * @param pjQrhf the value for adminresponsecase.PJ_QRHF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setPjQrhf(Integer pjQrhf) {
        this.pjQrhf = pjQrhf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.PJ_QRWF
     *
     * @return the value of adminresponsecase.PJ_QRWF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getPjQrwf() {
        return pjQrwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.PJ_QRWF
     *
     * @param pjQrwf the value for adminresponsecase.PJ_QRWF
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setPjQrwf(Integer pjQrwf) {
        this.pjQrwf = pjQrwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.PJ_BH
     *
     * @return the value of adminresponsecase.PJ_BH
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getPjBh() {
        return pjBh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.PJ_BH
     *
     * @param pjBh the value for adminresponsecase.PJ_BH
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setPjBh(Integer pjBh) {
        this.pjBh = pjBh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.PJ_PC
     *
     * @return the value of adminresponsecase.PJ_PC
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getPjPc() {
        return pjPc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.PJ_PC
     *
     * @param pjPc the value for adminresponsecase.PJ_PC
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setPjPc(Integer pjPc) {
        this.pjPc = pjPc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.PJ_BYPC
     *
     * @return the value of adminresponsecase.PJ_BYPC
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getPjBypc() {
        return pjBypc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.PJ_BYPC
     *
     * @param pjBypc the value for adminresponsecase.PJ_BYPC
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setPjBypc(Integer pjBypc) {
        this.pjBypc = pjBypc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.CD_BH
     *
     * @return the value of adminresponsecase.CD_BH
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getCdBh() {
        return cdBh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.CD_BH
     *
     * @param cdBh the value for adminresponsecase.CD_BH
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setCdBh(Integer cdBh) {
        this.cdBh = cdBh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.CD_CS_ZD
     *
     * @return the value of adminresponsecase.CD_CS_ZD
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getCdCsZd() {
        return cdCsZd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.CD_CS_ZD
     *
     * @param cdCsZd the value for adminresponsecase.CD_CS_ZD
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setCdCsZd(Integer cdCsZd) {
        this.cdCsZd = cdCsZd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.CD_CS_GB
     *
     * @return the value of adminresponsecase.CD_CS_GB
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getCdCsGb() {
        return cdCsGb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.CD_CS_GB
     *
     * @param cdCsGb the value for adminresponsecase.CD_CS_GB
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setCdCsGb(Integer cdCsGb) {
        this.cdCsGb = cdCsGb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.CD_YS
     *
     * @return the value of adminresponsecase.CD_YS
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getCdYs() {
        return cdYs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.CD_YS
     *
     * @param cdYs the value for adminresponsecase.CD_YS
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setCdYs(Integer cdYs) {
        this.cdYs = cdYs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.CD_ZJ
     *
     * @return the value of adminresponsecase.CD_ZJ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getCdZj() {
        return cdZj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.CD_ZJ
     *
     * @param cdZj the value for adminresponsecase.CD_ZJ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setCdZj(Integer cdZj) {
        this.cdZj = cdZj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.CD_QT
     *
     * @return the value of adminresponsecase.CD_QT
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getCdQt() {
        return cdQt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.CD_QT
     *
     * @param cdQt the value for adminresponsecase.CD_QT
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setCdQt(Integer cdQt) {
        this.cdQt = cdQt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.YSJA_PCTJ
     *
     * @return the value of adminresponsecase.YSJA_PCTJ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getYsjaPctj() {
        return ysjaPctj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.YSJA_PCTJ
     *
     * @param ysjaPctj the value for adminresponsecase.YSJA_PCTJ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setYsjaPctj(Integer ysjaPctj) {
        this.ysjaPctj = ysjaPctj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.WSJ
     *
     * @return the value of adminresponsecase.WSJ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getWsj() {
        return wsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.WSJ
     *
     * @param wsj the value for adminresponsecase.WSJ
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setWsj(Integer wsj) {
        this.wsj = wsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.Province
     *
     * @return the value of adminresponsecase.Province
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.Province
     *
     * @param province the value for adminresponsecase.Province
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.Year
     *
     * @return the value of adminresponsecase.Year
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.Year
     *
     * @param year the value for adminresponsecase.Year
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminresponsecase.SeqNo
     *
     * @return the value of adminresponsecase.SeqNo
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Integer getSeqno() {
        return seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminresponsecase.SeqNo
     *
     * @param seqno the value for adminresponsecase.SeqNo
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setSeqno(Integer seqno) {
        this.seqno = seqno;
    }
}