package com.ejunhai.qutihuo.statistical.model;

import java.util.ArrayList;
import java.util.List;

public class AdminresponsecaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public AdminresponsecaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSqjzIsNull() {
            addCriterion("SQJZ is null");
            return (Criteria) this;
        }

        public Criteria andSqjzIsNotNull() {
            addCriterion("SQJZ is not null");
            return (Criteria) this;
        }

        public Criteria andSqjzEqualTo(Integer value) {
            addCriterion("SQJZ =", value, "sqjz");
            return (Criteria) this;
        }

        public Criteria andSqjzNotEqualTo(Integer value) {
            addCriterion("SQJZ <>", value, "sqjz");
            return (Criteria) this;
        }

        public Criteria andSqjzGreaterThan(Integer value) {
            addCriterion("SQJZ >", value, "sqjz");
            return (Criteria) this;
        }

        public Criteria andSqjzGreaterThanOrEqualTo(Integer value) {
            addCriterion("SQJZ >=", value, "sqjz");
            return (Criteria) this;
        }

        public Criteria andSqjzLessThan(Integer value) {
            addCriterion("SQJZ <", value, "sqjz");
            return (Criteria) this;
        }

        public Criteria andSqjzLessThanOrEqualTo(Integer value) {
            addCriterion("SQJZ <=", value, "sqjz");
            return (Criteria) this;
        }

        public Criteria andSqjzIn(List<Integer> values) {
            addCriterion("SQJZ in", values, "sqjz");
            return (Criteria) this;
        }

        public Criteria andSqjzNotIn(List<Integer> values) {
            addCriterion("SQJZ not in", values, "sqjz");
            return (Criteria) this;
        }

        public Criteria andSqjzBetween(Integer value1, Integer value2) {
            addCriterion("SQJZ between", value1, value2, "sqjz");
            return (Criteria) this;
        }

        public Criteria andSqjzNotBetween(Integer value1, Integer value2) {
            addCriterion("SQJZ not between", value1, value2, "sqjz");
            return (Criteria) this;
        }

        public Criteria andBqfsFyhysIsNull() {
            addCriterion("BQFS_FYHYS is null");
            return (Criteria) this;
        }

        public Criteria andBqfsFyhysIsNotNull() {
            addCriterion("BQFS_FYHYS is not null");
            return (Criteria) this;
        }

        public Criteria andBqfsFyhysEqualTo(Integer value) {
            addCriterion("BQFS_FYHYS =", value, "bqfsFyhys");
            return (Criteria) this;
        }

        public Criteria andBqfsFyhysNotEqualTo(Integer value) {
            addCriterion("BQFS_FYHYS <>", value, "bqfsFyhys");
            return (Criteria) this;
        }

        public Criteria andBqfsFyhysGreaterThan(Integer value) {
            addCriterion("BQFS_FYHYS >", value, "bqfsFyhys");
            return (Criteria) this;
        }

        public Criteria andBqfsFyhysGreaterThanOrEqualTo(Integer value) {
            addCriterion("BQFS_FYHYS >=", value, "bqfsFyhys");
            return (Criteria) this;
        }

        public Criteria andBqfsFyhysLessThan(Integer value) {
            addCriterion("BQFS_FYHYS <", value, "bqfsFyhys");
            return (Criteria) this;
        }

        public Criteria andBqfsFyhysLessThanOrEqualTo(Integer value) {
            addCriterion("BQFS_FYHYS <=", value, "bqfsFyhys");
            return (Criteria) this;
        }

        public Criteria andBqfsFyhysIn(List<Integer> values) {
            addCriterion("BQFS_FYHYS in", values, "bqfsFyhys");
            return (Criteria) this;
        }

        public Criteria andBqfsFyhysNotIn(List<Integer> values) {
            addCriterion("BQFS_FYHYS not in", values, "bqfsFyhys");
            return (Criteria) this;
        }

        public Criteria andBqfsFyhysBetween(Integer value1, Integer value2) {
            addCriterion("BQFS_FYHYS between", value1, value2, "bqfsFyhys");
            return (Criteria) this;
        }

        public Criteria andBqfsFyhysNotBetween(Integer value1, Integer value2) {
            addCriterion("BQFS_FYHYS not between", value1, value2, "bqfsFyhys");
            return (Criteria) this;
        }

        public Criteria andBqfsWjfyzjysIsNull() {
            addCriterion("BQFS_WJFYZJYS is null");
            return (Criteria) this;
        }

        public Criteria andBqfsWjfyzjysIsNotNull() {
            addCriterion("BQFS_WJFYZJYS is not null");
            return (Criteria) this;
        }

        public Criteria andBqfsWjfyzjysEqualTo(Integer value) {
            addCriterion("BQFS_WJFYZJYS =", value, "bqfsWjfyzjys");
            return (Criteria) this;
        }

        public Criteria andBqfsWjfyzjysNotEqualTo(Integer value) {
            addCriterion("BQFS_WJFYZJYS <>", value, "bqfsWjfyzjys");
            return (Criteria) this;
        }

        public Criteria andBqfsWjfyzjysGreaterThan(Integer value) {
            addCriterion("BQFS_WJFYZJYS >", value, "bqfsWjfyzjys");
            return (Criteria) this;
        }

        public Criteria andBqfsWjfyzjysGreaterThanOrEqualTo(Integer value) {
            addCriterion("BQFS_WJFYZJYS >=", value, "bqfsWjfyzjys");
            return (Criteria) this;
        }

        public Criteria andBqfsWjfyzjysLessThan(Integer value) {
            addCriterion("BQFS_WJFYZJYS <", value, "bqfsWjfyzjys");
            return (Criteria) this;
        }

        public Criteria andBqfsWjfyzjysLessThanOrEqualTo(Integer value) {
            addCriterion("BQFS_WJFYZJYS <=", value, "bqfsWjfyzjys");
            return (Criteria) this;
        }

        public Criteria andBqfsWjfyzjysIn(List<Integer> values) {
            addCriterion("BQFS_WJFYZJYS in", values, "bqfsWjfyzjys");
            return (Criteria) this;
        }

        public Criteria andBqfsWjfyzjysNotIn(List<Integer> values) {
            addCriterion("BQFS_WJFYZJYS not in", values, "bqfsWjfyzjys");
            return (Criteria) this;
        }

        public Criteria andBqfsWjfyzjysBetween(Integer value1, Integer value2) {
            addCriterion("BQFS_WJFYZJYS between", value1, value2, "bqfsWjfyzjys");
            return (Criteria) this;
        }

        public Criteria andBqfsWjfyzjysNotBetween(Integer value1, Integer value2) {
            addCriterion("BQFS_WJFYZJYS not between", value1, value2, "bqfsWjfyzjys");
            return (Criteria) this;
        }

        public Criteria andYsjgYjtxzxwjgIsNull() {
            addCriterion("YSJG_YJTXZXWJG is null");
            return (Criteria) this;
        }

        public Criteria andYsjgYjtxzxwjgIsNotNull() {
            addCriterion("YSJG_YJTXZXWJG is not null");
            return (Criteria) this;
        }

        public Criteria andYsjgYjtxzxwjgEqualTo(Integer value) {
            addCriterion("YSJG_YJTXZXWJG =", value, "ysjgYjtxzxwjg");
            return (Criteria) this;
        }

        public Criteria andYsjgYjtxzxwjgNotEqualTo(Integer value) {
            addCriterion("YSJG_YJTXZXWJG <>", value, "ysjgYjtxzxwjg");
            return (Criteria) this;
        }

        public Criteria andYsjgYjtxzxwjgGreaterThan(Integer value) {
            addCriterion("YSJG_YJTXZXWJG >", value, "ysjgYjtxzxwjg");
            return (Criteria) this;
        }

        public Criteria andYsjgYjtxzxwjgGreaterThanOrEqualTo(Integer value) {
            addCriterion("YSJG_YJTXZXWJG >=", value, "ysjgYjtxzxwjg");
            return (Criteria) this;
        }

        public Criteria andYsjgYjtxzxwjgLessThan(Integer value) {
            addCriterion("YSJG_YJTXZXWJG <", value, "ysjgYjtxzxwjg");
            return (Criteria) this;
        }

        public Criteria andYsjgYjtxzxwjgLessThanOrEqualTo(Integer value) {
            addCriterion("YSJG_YJTXZXWJG <=", value, "ysjgYjtxzxwjg");
            return (Criteria) this;
        }

        public Criteria andYsjgYjtxzxwjgIn(List<Integer> values) {
            addCriterion("YSJG_YJTXZXWJG in", values, "ysjgYjtxzxwjg");
            return (Criteria) this;
        }

        public Criteria andYsjgYjtxzxwjgNotIn(List<Integer> values) {
            addCriterion("YSJG_YJTXZXWJG not in", values, "ysjgYjtxzxwjg");
            return (Criteria) this;
        }

        public Criteria andYsjgYjtxzxwjgBetween(Integer value1, Integer value2) {
            addCriterion("YSJG_YJTXZXWJG between", value1, value2, "ysjgYjtxzxwjg");
            return (Criteria) this;
        }

        public Criteria andYsjgYjtxzxwjgNotBetween(Integer value1, Integer value2) {
            addCriterion("YSJG_YJTXZXWJG not between", value1, value2, "ysjgYjtxzxwjg");
            return (Criteria) this;
        }

        public Criteria andYsjgFyjgIsNull() {
            addCriterion("YSJG_FYJG is null");
            return (Criteria) this;
        }

        public Criteria andYsjgFyjgIsNotNull() {
            addCriterion("YSJG_FYJG is not null");
            return (Criteria) this;
        }

        public Criteria andYsjgFyjgEqualTo(Integer value) {
            addCriterion("YSJG_FYJG =", value, "ysjgFyjg");
            return (Criteria) this;
        }

        public Criteria andYsjgFyjgNotEqualTo(Integer value) {
            addCriterion("YSJG_FYJG <>", value, "ysjgFyjg");
            return (Criteria) this;
        }

        public Criteria andYsjgFyjgGreaterThan(Integer value) {
            addCriterion("YSJG_FYJG >", value, "ysjgFyjg");
            return (Criteria) this;
        }

        public Criteria andYsjgFyjgGreaterThanOrEqualTo(Integer value) {
            addCriterion("YSJG_FYJG >=", value, "ysjgFyjg");
            return (Criteria) this;
        }

        public Criteria andYsjgFyjgLessThan(Integer value) {
            addCriterion("YSJG_FYJG <", value, "ysjgFyjg");
            return (Criteria) this;
        }

        public Criteria andYsjgFyjgLessThanOrEqualTo(Integer value) {
            addCriterion("YSJG_FYJG <=", value, "ysjgFyjg");
            return (Criteria) this;
        }

        public Criteria andYsjgFyjgIn(List<Integer> values) {
            addCriterion("YSJG_FYJG in", values, "ysjgFyjg");
            return (Criteria) this;
        }

        public Criteria andYsjgFyjgNotIn(List<Integer> values) {
            addCriterion("YSJG_FYJG not in", values, "ysjgFyjg");
            return (Criteria) this;
        }

        public Criteria andYsjgFyjgBetween(Integer value1, Integer value2) {
            addCriterion("YSJG_FYJG between", value1, value2, "ysjgFyjg");
            return (Criteria) this;
        }

        public Criteria andYsjgFyjgNotBetween(Integer value1, Integer value2) {
            addCriterion("YSJG_FYJG not between", value1, value2, "ysjgFyjg");
            return (Criteria) this;
        }

        public Criteria andYsjgXzzfIsNull() {
            addCriterion("YSJG_XZZF is null");
            return (Criteria) this;
        }

        public Criteria andYsjgXzzfIsNotNull() {
            addCriterion("YSJG_XZZF is not null");
            return (Criteria) this;
        }

        public Criteria andYsjgXzzfEqualTo(Integer value) {
            addCriterion("YSJG_XZZF =", value, "ysjgXzzf");
            return (Criteria) this;
        }

        public Criteria andYsjgXzzfNotEqualTo(Integer value) {
            addCriterion("YSJG_XZZF <>", value, "ysjgXzzf");
            return (Criteria) this;
        }

        public Criteria andYsjgXzzfGreaterThan(Integer value) {
            addCriterion("YSJG_XZZF >", value, "ysjgXzzf");
            return (Criteria) this;
        }

        public Criteria andYsjgXzzfGreaterThanOrEqualTo(Integer value) {
            addCriterion("YSJG_XZZF >=", value, "ysjgXzzf");
            return (Criteria) this;
        }

        public Criteria andYsjgXzzfLessThan(Integer value) {
            addCriterion("YSJG_XZZF <", value, "ysjgXzzf");
            return (Criteria) this;
        }

        public Criteria andYsjgXzzfLessThanOrEqualTo(Integer value) {
            addCriterion("YSJG_XZZF <=", value, "ysjgXzzf");
            return (Criteria) this;
        }

        public Criteria andYsjgXzzfIn(List<Integer> values) {
            addCriterion("YSJG_XZZF in", values, "ysjgXzzf");
            return (Criteria) this;
        }

        public Criteria andYsjgXzzfNotIn(List<Integer> values) {
            addCriterion("YSJG_XZZF not in", values, "ysjgXzzf");
            return (Criteria) this;
        }

        public Criteria andYsjgXzzfBetween(Integer value1, Integer value2) {
            addCriterion("YSJG_XZZF between", value1, value2, "ysjgXzzf");
            return (Criteria) this;
        }

        public Criteria andYsjgXzzfNotBetween(Integer value1, Integer value2) {
            addCriterion("YSJG_XZZF not between", value1, value2, "ysjgXzzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjbmIsNull() {
            addCriterion("YSJGJB_XJBM is null");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjbmIsNotNull() {
            addCriterion("YSJGJB_XJBM is not null");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjbmEqualTo(Integer value) {
            addCriterion("YSJGJB_XJBM =", value, "ysjgjbXjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjbmNotEqualTo(Integer value) {
            addCriterion("YSJGJB_XJBM <>", value, "ysjgjbXjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjbmGreaterThan(Integer value) {
            addCriterion("YSJGJB_XJBM >", value, "ysjgjbXjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("YSJGJB_XJBM >=", value, "ysjgjbXjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjbmLessThan(Integer value) {
            addCriterion("YSJGJB_XJBM <", value, "ysjgjbXjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjbmLessThanOrEqualTo(Integer value) {
            addCriterion("YSJGJB_XJBM <=", value, "ysjgjbXjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjbmIn(List<Integer> values) {
            addCriterion("YSJGJB_XJBM in", values, "ysjgjbXjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjbmNotIn(List<Integer> values) {
            addCriterion("YSJGJB_XJBM not in", values, "ysjgjbXjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjbmBetween(Integer value1, Integer value2) {
            addCriterion("YSJGJB_XJBM between", value1, value2, "ysjgjbXjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjbmNotBetween(Integer value1, Integer value2) {
            addCriterion("YSJGJB_XJBM not between", value1, value2, "ysjgjbXjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjzfIsNull() {
            addCriterion("YSJGJB_XJZF is null");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjzfIsNotNull() {
            addCriterion("YSJGJB_XJZF is not null");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjzfEqualTo(Integer value) {
            addCriterion("YSJGJB_XJZF =", value, "ysjgjbXjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjzfNotEqualTo(Integer value) {
            addCriterion("YSJGJB_XJZF <>", value, "ysjgjbXjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjzfGreaterThan(Integer value) {
            addCriterion("YSJGJB_XJZF >", value, "ysjgjbXjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjzfGreaterThanOrEqualTo(Integer value) {
            addCriterion("YSJGJB_XJZF >=", value, "ysjgjbXjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjzfLessThan(Integer value) {
            addCriterion("YSJGJB_XJZF <", value, "ysjgjbXjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjzfLessThanOrEqualTo(Integer value) {
            addCriterion("YSJGJB_XJZF <=", value, "ysjgjbXjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjzfIn(List<Integer> values) {
            addCriterion("YSJGJB_XJZF in", values, "ysjgjbXjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjzfNotIn(List<Integer> values) {
            addCriterion("YSJGJB_XJZF not in", values, "ysjgjbXjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjzfBetween(Integer value1, Integer value2) {
            addCriterion("YSJGJB_XJZF between", value1, value2, "ysjgjbXjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbXjzfNotBetween(Integer value1, Integer value2) {
            addCriterion("YSJGJB_XJZF not between", value1, value2, "ysjgjbXjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjbmIsNull() {
            addCriterion("YSJGJB_DJBM is null");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjbmIsNotNull() {
            addCriterion("YSJGJB_DJBM is not null");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjbmEqualTo(Integer value) {
            addCriterion("YSJGJB_DJBM =", value, "ysjgjbDjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjbmNotEqualTo(Integer value) {
            addCriterion("YSJGJB_DJBM <>", value, "ysjgjbDjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjbmGreaterThan(Integer value) {
            addCriterion("YSJGJB_DJBM >", value, "ysjgjbDjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("YSJGJB_DJBM >=", value, "ysjgjbDjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjbmLessThan(Integer value) {
            addCriterion("YSJGJB_DJBM <", value, "ysjgjbDjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjbmLessThanOrEqualTo(Integer value) {
            addCriterion("YSJGJB_DJBM <=", value, "ysjgjbDjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjbmIn(List<Integer> values) {
            addCriterion("YSJGJB_DJBM in", values, "ysjgjbDjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjbmNotIn(List<Integer> values) {
            addCriterion("YSJGJB_DJBM not in", values, "ysjgjbDjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjbmBetween(Integer value1, Integer value2) {
            addCriterion("YSJGJB_DJBM between", value1, value2, "ysjgjbDjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjbmNotBetween(Integer value1, Integer value2) {
            addCriterion("YSJGJB_DJBM not between", value1, value2, "ysjgjbDjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjzfIsNull() {
            addCriterion("YSJGJB_DJZF is null");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjzfIsNotNull() {
            addCriterion("YSJGJB_DJZF is not null");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjzfEqualTo(Integer value) {
            addCriterion("YSJGJB_DJZF =", value, "ysjgjbDjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjzfNotEqualTo(Integer value) {
            addCriterion("YSJGJB_DJZF <>", value, "ysjgjbDjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjzfGreaterThan(Integer value) {
            addCriterion("YSJGJB_DJZF >", value, "ysjgjbDjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjzfGreaterThanOrEqualTo(Integer value) {
            addCriterion("YSJGJB_DJZF >=", value, "ysjgjbDjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjzfLessThan(Integer value) {
            addCriterion("YSJGJB_DJZF <", value, "ysjgjbDjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjzfLessThanOrEqualTo(Integer value) {
            addCriterion("YSJGJB_DJZF <=", value, "ysjgjbDjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjzfIn(List<Integer> values) {
            addCriterion("YSJGJB_DJZF in", values, "ysjgjbDjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjzfNotIn(List<Integer> values) {
            addCriterion("YSJGJB_DJZF not in", values, "ysjgjbDjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjzfBetween(Integer value1, Integer value2) {
            addCriterion("YSJGJB_DJZF between", value1, value2, "ysjgjbDjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbDjzfNotBetween(Integer value1, Integer value2) {
            addCriterion("YSJGJB_DJZF not between", value1, value2, "ysjgjbDjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjbmIsNull() {
            addCriterion("YSJGJB_SJBM is null");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjbmIsNotNull() {
            addCriterion("YSJGJB_SJBM is not null");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjbmEqualTo(Integer value) {
            addCriterion("YSJGJB_SJBM =", value, "ysjgjbSjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjbmNotEqualTo(Integer value) {
            addCriterion("YSJGJB_SJBM <>", value, "ysjgjbSjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjbmGreaterThan(Integer value) {
            addCriterion("YSJGJB_SJBM >", value, "ysjgjbSjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("YSJGJB_SJBM >=", value, "ysjgjbSjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjbmLessThan(Integer value) {
            addCriterion("YSJGJB_SJBM <", value, "ysjgjbSjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjbmLessThanOrEqualTo(Integer value) {
            addCriterion("YSJGJB_SJBM <=", value, "ysjgjbSjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjbmIn(List<Integer> values) {
            addCriterion("YSJGJB_SJBM in", values, "ysjgjbSjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjbmNotIn(List<Integer> values) {
            addCriterion("YSJGJB_SJBM not in", values, "ysjgjbSjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjbmBetween(Integer value1, Integer value2) {
            addCriterion("YSJGJB_SJBM between", value1, value2, "ysjgjbSjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjbmNotBetween(Integer value1, Integer value2) {
            addCriterion("YSJGJB_SJBM not between", value1, value2, "ysjgjbSjbm");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjzfIsNull() {
            addCriterion("YSJGJB_SJZF is null");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjzfIsNotNull() {
            addCriterion("YSJGJB_SJZF is not null");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjzfEqualTo(Integer value) {
            addCriterion("YSJGJB_SJZF =", value, "ysjgjbSjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjzfNotEqualTo(Integer value) {
            addCriterion("YSJGJB_SJZF <>", value, "ysjgjbSjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjzfGreaterThan(Integer value) {
            addCriterion("YSJGJB_SJZF >", value, "ysjgjbSjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjzfGreaterThanOrEqualTo(Integer value) {
            addCriterion("YSJGJB_SJZF >=", value, "ysjgjbSjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjzfLessThan(Integer value) {
            addCriterion("YSJGJB_SJZF <", value, "ysjgjbSjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjzfLessThanOrEqualTo(Integer value) {
            addCriterion("YSJGJB_SJZF <=", value, "ysjgjbSjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjzfIn(List<Integer> values) {
            addCriterion("YSJGJB_SJZF in", values, "ysjgjbSjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjzfNotIn(List<Integer> values) {
            addCriterion("YSJGJB_SJZF not in", values, "ysjgjbSjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjzfBetween(Integer value1, Integer value2) {
            addCriterion("YSJGJB_SJZF between", value1, value2, "ysjgjbSjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbSjzfNotBetween(Integer value1, Integer value2) {
            addCriterion("YSJGJB_SJZF not between", value1, value2, "ysjgjbSjzf");
            return (Criteria) this;
        }

        public Criteria andYsjgjbQtIsNull() {
            addCriterion("YSJGJB_QT is null");
            return (Criteria) this;
        }

        public Criteria andYsjgjbQtIsNotNull() {
            addCriterion("YSJGJB_QT is not null");
            return (Criteria) this;
        }

        public Criteria andYsjgjbQtEqualTo(Integer value) {
            addCriterion("YSJGJB_QT =", value, "ysjgjbQt");
            return (Criteria) this;
        }

        public Criteria andYsjgjbQtNotEqualTo(Integer value) {
            addCriterion("YSJGJB_QT <>", value, "ysjgjbQt");
            return (Criteria) this;
        }

        public Criteria andYsjgjbQtGreaterThan(Integer value) {
            addCriterion("YSJGJB_QT >", value, "ysjgjbQt");
            return (Criteria) this;
        }

        public Criteria andYsjgjbQtGreaterThanOrEqualTo(Integer value) {
            addCriterion("YSJGJB_QT >=", value, "ysjgjbQt");
            return (Criteria) this;
        }

        public Criteria andYsjgjbQtLessThan(Integer value) {
            addCriterion("YSJGJB_QT <", value, "ysjgjbQt");
            return (Criteria) this;
        }

        public Criteria andYsjgjbQtLessThanOrEqualTo(Integer value) {
            addCriterion("YSJGJB_QT <=", value, "ysjgjbQt");
            return (Criteria) this;
        }

        public Criteria andYsjgjbQtIn(List<Integer> values) {
            addCriterion("YSJGJB_QT in", values, "ysjgjbQt");
            return (Criteria) this;
        }

        public Criteria andYsjgjbQtNotIn(List<Integer> values) {
            addCriterion("YSJGJB_QT not in", values, "ysjgjbQt");
            return (Criteria) this;
        }

        public Criteria andYsjgjbQtBetween(Integer value1, Integer value2) {
            addCriterion("YSJGJB_QT between", value1, value2, "ysjgjbQt");
            return (Criteria) this;
        }

        public Criteria andYsjgjbQtNotBetween(Integer value1, Integer value2) {
            addCriterion("YSJGJB_QT not between", value1, value2, "ysjgjbQt");
            return (Criteria) this;
        }

        public Criteria andPjWcIsNull() {
            addCriterion("PJ_WC is null");
            return (Criteria) this;
        }

        public Criteria andPjWcIsNotNull() {
            addCriterion("PJ_WC is not null");
            return (Criteria) this;
        }

        public Criteria andPjWcEqualTo(Integer value) {
            addCriterion("PJ_WC =", value, "pjWc");
            return (Criteria) this;
        }

        public Criteria andPjWcNotEqualTo(Integer value) {
            addCriterion("PJ_WC <>", value, "pjWc");
            return (Criteria) this;
        }

        public Criteria andPjWcGreaterThan(Integer value) {
            addCriterion("PJ_WC >", value, "pjWc");
            return (Criteria) this;
        }

        public Criteria andPjWcGreaterThanOrEqualTo(Integer value) {
            addCriterion("PJ_WC >=", value, "pjWc");
            return (Criteria) this;
        }

        public Criteria andPjWcLessThan(Integer value) {
            addCriterion("PJ_WC <", value, "pjWc");
            return (Criteria) this;
        }

        public Criteria andPjWcLessThanOrEqualTo(Integer value) {
            addCriterion("PJ_WC <=", value, "pjWc");
            return (Criteria) this;
        }

        public Criteria andPjWcIn(List<Integer> values) {
            addCriterion("PJ_WC in", values, "pjWc");
            return (Criteria) this;
        }

        public Criteria andPjWcNotIn(List<Integer> values) {
            addCriterion("PJ_WC not in", values, "pjWc");
            return (Criteria) this;
        }

        public Criteria andPjWcBetween(Integer value1, Integer value2) {
            addCriterion("PJ_WC between", value1, value2, "pjWc");
            return (Criteria) this;
        }

        public Criteria andPjWcNotBetween(Integer value1, Integer value2) {
            addCriterion("PJ_WC not between", value1, value2, "pjWc");
            return (Criteria) this;
        }

        public Criteria andPjCxQbIsNull() {
            addCriterion("PJ_CX_QB is null");
            return (Criteria) this;
        }

        public Criteria andPjCxQbIsNotNull() {
            addCriterion("PJ_CX_QB is not null");
            return (Criteria) this;
        }

        public Criteria andPjCxQbEqualTo(Integer value) {
            addCriterion("PJ_CX_QB =", value, "pjCxQb");
            return (Criteria) this;
        }

        public Criteria andPjCxQbNotEqualTo(Integer value) {
            addCriterion("PJ_CX_QB <>", value, "pjCxQb");
            return (Criteria) this;
        }

        public Criteria andPjCxQbGreaterThan(Integer value) {
            addCriterion("PJ_CX_QB >", value, "pjCxQb");
            return (Criteria) this;
        }

        public Criteria andPjCxQbGreaterThanOrEqualTo(Integer value) {
            addCriterion("PJ_CX_QB >=", value, "pjCxQb");
            return (Criteria) this;
        }

        public Criteria andPjCxQbLessThan(Integer value) {
            addCriterion("PJ_CX_QB <", value, "pjCxQb");
            return (Criteria) this;
        }

        public Criteria andPjCxQbLessThanOrEqualTo(Integer value) {
            addCriterion("PJ_CX_QB <=", value, "pjCxQb");
            return (Criteria) this;
        }

        public Criteria andPjCxQbIn(List<Integer> values) {
            addCriterion("PJ_CX_QB in", values, "pjCxQb");
            return (Criteria) this;
        }

        public Criteria andPjCxQbNotIn(List<Integer> values) {
            addCriterion("PJ_CX_QB not in", values, "pjCxQb");
            return (Criteria) this;
        }

        public Criteria andPjCxQbBetween(Integer value1, Integer value2) {
            addCriterion("PJ_CX_QB between", value1, value2, "pjCxQb");
            return (Criteria) this;
        }

        public Criteria andPjCxQbNotBetween(Integer value1, Integer value2) {
            addCriterion("PJ_CX_QB not between", value1, value2, "pjCxQb");
            return (Criteria) this;
        }

        public Criteria andPjCxBfIsNull() {
            addCriterion("PJ_CX_BF is null");
            return (Criteria) this;
        }

        public Criteria andPjCxBfIsNotNull() {
            addCriterion("PJ_CX_BF is not null");
            return (Criteria) this;
        }

        public Criteria andPjCxBfEqualTo(Integer value) {
            addCriterion("PJ_CX_BF =", value, "pjCxBf");
            return (Criteria) this;
        }

        public Criteria andPjCxBfNotEqualTo(Integer value) {
            addCriterion("PJ_CX_BF <>", value, "pjCxBf");
            return (Criteria) this;
        }

        public Criteria andPjCxBfGreaterThan(Integer value) {
            addCriterion("PJ_CX_BF >", value, "pjCxBf");
            return (Criteria) this;
        }

        public Criteria andPjCxBfGreaterThanOrEqualTo(Integer value) {
            addCriterion("PJ_CX_BF >=", value, "pjCxBf");
            return (Criteria) this;
        }

        public Criteria andPjCxBfLessThan(Integer value) {
            addCriterion("PJ_CX_BF <", value, "pjCxBf");
            return (Criteria) this;
        }

        public Criteria andPjCxBfLessThanOrEqualTo(Integer value) {
            addCriterion("PJ_CX_BF <=", value, "pjCxBf");
            return (Criteria) this;
        }

        public Criteria andPjCxBfIn(List<Integer> values) {
            addCriterion("PJ_CX_BF in", values, "pjCxBf");
            return (Criteria) this;
        }

        public Criteria andPjCxBfNotIn(List<Integer> values) {
            addCriterion("PJ_CX_BF not in", values, "pjCxBf");
            return (Criteria) this;
        }

        public Criteria andPjCxBfBetween(Integer value1, Integer value2) {
            addCriterion("PJ_CX_BF between", value1, value2, "pjCxBf");
            return (Criteria) this;
        }

        public Criteria andPjCxBfNotBetween(Integer value1, Integer value2) {
            addCriterion("PJ_CX_BF not between", value1, value2, "pjCxBf");
            return (Criteria) this;
        }

        public Criteria andPjCxCxIsNull() {
            addCriterion("PJ_CX_CX is null");
            return (Criteria) this;
        }

        public Criteria andPjCxCxIsNotNull() {
            addCriterion("PJ_CX_CX is not null");
            return (Criteria) this;
        }

        public Criteria andPjCxCxEqualTo(Integer value) {
            addCriterion("PJ_CX_CX =", value, "pjCxCx");
            return (Criteria) this;
        }

        public Criteria andPjCxCxNotEqualTo(Integer value) {
            addCriterion("PJ_CX_CX <>", value, "pjCxCx");
            return (Criteria) this;
        }

        public Criteria andPjCxCxGreaterThan(Integer value) {
            addCriterion("PJ_CX_CX >", value, "pjCxCx");
            return (Criteria) this;
        }

        public Criteria andPjCxCxGreaterThanOrEqualTo(Integer value) {
            addCriterion("PJ_CX_CX >=", value, "pjCxCx");
            return (Criteria) this;
        }

        public Criteria andPjCxCxLessThan(Integer value) {
            addCriterion("PJ_CX_CX <", value, "pjCxCx");
            return (Criteria) this;
        }

        public Criteria andPjCxCxLessThanOrEqualTo(Integer value) {
            addCriterion("PJ_CX_CX <=", value, "pjCxCx");
            return (Criteria) this;
        }

        public Criteria andPjCxCxIn(List<Integer> values) {
            addCriterion("PJ_CX_CX in", values, "pjCxCx");
            return (Criteria) this;
        }

        public Criteria andPjCxCxNotIn(List<Integer> values) {
            addCriterion("PJ_CX_CX not in", values, "pjCxCx");
            return (Criteria) this;
        }

        public Criteria andPjCxCxBetween(Integer value1, Integer value2) {
            addCriterion("PJ_CX_CX between", value1, value2, "pjCxCx");
            return (Criteria) this;
        }

        public Criteria andPjCxCxNotBetween(Integer value1, Integer value2) {
            addCriterion("PJ_CX_CX not between", value1, value2, "pjCxCx");
            return (Criteria) this;
        }

        public Criteria andPjBgIsNull() {
            addCriterion("PJ_BG is null");
            return (Criteria) this;
        }

        public Criteria andPjBgIsNotNull() {
            addCriterion("PJ_BG is not null");
            return (Criteria) this;
        }

        public Criteria andPjBgEqualTo(Integer value) {
            addCriterion("PJ_BG =", value, "pjBg");
            return (Criteria) this;
        }

        public Criteria andPjBgNotEqualTo(Integer value) {
            addCriterion("PJ_BG <>", value, "pjBg");
            return (Criteria) this;
        }

        public Criteria andPjBgGreaterThan(Integer value) {
            addCriterion("PJ_BG >", value, "pjBg");
            return (Criteria) this;
        }

        public Criteria andPjBgGreaterThanOrEqualTo(Integer value) {
            addCriterion("PJ_BG >=", value, "pjBg");
            return (Criteria) this;
        }

        public Criteria andPjBgLessThan(Integer value) {
            addCriterion("PJ_BG <", value, "pjBg");
            return (Criteria) this;
        }

        public Criteria andPjBgLessThanOrEqualTo(Integer value) {
            addCriterion("PJ_BG <=", value, "pjBg");
            return (Criteria) this;
        }

        public Criteria andPjBgIn(List<Integer> values) {
            addCriterion("PJ_BG in", values, "pjBg");
            return (Criteria) this;
        }

        public Criteria andPjBgNotIn(List<Integer> values) {
            addCriterion("PJ_BG not in", values, "pjBg");
            return (Criteria) this;
        }

        public Criteria andPjBgBetween(Integer value1, Integer value2) {
            addCriterion("PJ_BG between", value1, value2, "pjBg");
            return (Criteria) this;
        }

        public Criteria andPjBgNotBetween(Integer value1, Integer value2) {
            addCriterion("PJ_BG not between", value1, value2, "pjBg");
            return (Criteria) this;
        }

        public Criteria andPjLxfdzzIsNull() {
            addCriterion("PJ_LXFDZZ is null");
            return (Criteria) this;
        }

        public Criteria andPjLxfdzzIsNotNull() {
            addCriterion("PJ_LXFDZZ is not null");
            return (Criteria) this;
        }

        public Criteria andPjLxfdzzEqualTo(Integer value) {
            addCriterion("PJ_LXFDZZ =", value, "pjLxfdzz");
            return (Criteria) this;
        }

        public Criteria andPjLxfdzzNotEqualTo(Integer value) {
            addCriterion("PJ_LXFDZZ <>", value, "pjLxfdzz");
            return (Criteria) this;
        }

        public Criteria andPjLxfdzzGreaterThan(Integer value) {
            addCriterion("PJ_LXFDZZ >", value, "pjLxfdzz");
            return (Criteria) this;
        }

        public Criteria andPjLxfdzzGreaterThanOrEqualTo(Integer value) {
            addCriterion("PJ_LXFDZZ >=", value, "pjLxfdzz");
            return (Criteria) this;
        }

        public Criteria andPjLxfdzzLessThan(Integer value) {
            addCriterion("PJ_LXFDZZ <", value, "pjLxfdzz");
            return (Criteria) this;
        }

        public Criteria andPjLxfdzzLessThanOrEqualTo(Integer value) {
            addCriterion("PJ_LXFDZZ <=", value, "pjLxfdzz");
            return (Criteria) this;
        }

        public Criteria andPjLxfdzzIn(List<Integer> values) {
            addCriterion("PJ_LXFDZZ in", values, "pjLxfdzz");
            return (Criteria) this;
        }

        public Criteria andPjLxfdzzNotIn(List<Integer> values) {
            addCriterion("PJ_LXFDZZ not in", values, "pjLxfdzz");
            return (Criteria) this;
        }

        public Criteria andPjLxfdzzBetween(Integer value1, Integer value2) {
            addCriterion("PJ_LXFDZZ between", value1, value2, "pjLxfdzz");
            return (Criteria) this;
        }

        public Criteria andPjLxfdzzNotBetween(Integer value1, Integer value2) {
            addCriterion("PJ_LXFDZZ not between", value1, value2, "pjLxfdzz");
            return (Criteria) this;
        }

        public Criteria andPjQrhfIsNull() {
            addCriterion("PJ_QRHF is null");
            return (Criteria) this;
        }

        public Criteria andPjQrhfIsNotNull() {
            addCriterion("PJ_QRHF is not null");
            return (Criteria) this;
        }

        public Criteria andPjQrhfEqualTo(Integer value) {
            addCriterion("PJ_QRHF =", value, "pjQrhf");
            return (Criteria) this;
        }

        public Criteria andPjQrhfNotEqualTo(Integer value) {
            addCriterion("PJ_QRHF <>", value, "pjQrhf");
            return (Criteria) this;
        }

        public Criteria andPjQrhfGreaterThan(Integer value) {
            addCriterion("PJ_QRHF >", value, "pjQrhf");
            return (Criteria) this;
        }

        public Criteria andPjQrhfGreaterThanOrEqualTo(Integer value) {
            addCriterion("PJ_QRHF >=", value, "pjQrhf");
            return (Criteria) this;
        }

        public Criteria andPjQrhfLessThan(Integer value) {
            addCriterion("PJ_QRHF <", value, "pjQrhf");
            return (Criteria) this;
        }

        public Criteria andPjQrhfLessThanOrEqualTo(Integer value) {
            addCriterion("PJ_QRHF <=", value, "pjQrhf");
            return (Criteria) this;
        }

        public Criteria andPjQrhfIn(List<Integer> values) {
            addCriterion("PJ_QRHF in", values, "pjQrhf");
            return (Criteria) this;
        }

        public Criteria andPjQrhfNotIn(List<Integer> values) {
            addCriterion("PJ_QRHF not in", values, "pjQrhf");
            return (Criteria) this;
        }

        public Criteria andPjQrhfBetween(Integer value1, Integer value2) {
            addCriterion("PJ_QRHF between", value1, value2, "pjQrhf");
            return (Criteria) this;
        }

        public Criteria andPjQrhfNotBetween(Integer value1, Integer value2) {
            addCriterion("PJ_QRHF not between", value1, value2, "pjQrhf");
            return (Criteria) this;
        }

        public Criteria andPjQrwfIsNull() {
            addCriterion("PJ_QRWF is null");
            return (Criteria) this;
        }

        public Criteria andPjQrwfIsNotNull() {
            addCriterion("PJ_QRWF is not null");
            return (Criteria) this;
        }

        public Criteria andPjQrwfEqualTo(Integer value) {
            addCriterion("PJ_QRWF =", value, "pjQrwf");
            return (Criteria) this;
        }

        public Criteria andPjQrwfNotEqualTo(Integer value) {
            addCriterion("PJ_QRWF <>", value, "pjQrwf");
            return (Criteria) this;
        }

        public Criteria andPjQrwfGreaterThan(Integer value) {
            addCriterion("PJ_QRWF >", value, "pjQrwf");
            return (Criteria) this;
        }

        public Criteria andPjQrwfGreaterThanOrEqualTo(Integer value) {
            addCriterion("PJ_QRWF >=", value, "pjQrwf");
            return (Criteria) this;
        }

        public Criteria andPjQrwfLessThan(Integer value) {
            addCriterion("PJ_QRWF <", value, "pjQrwf");
            return (Criteria) this;
        }

        public Criteria andPjQrwfLessThanOrEqualTo(Integer value) {
            addCriterion("PJ_QRWF <=", value, "pjQrwf");
            return (Criteria) this;
        }

        public Criteria andPjQrwfIn(List<Integer> values) {
            addCriterion("PJ_QRWF in", values, "pjQrwf");
            return (Criteria) this;
        }

        public Criteria andPjQrwfNotIn(List<Integer> values) {
            addCriterion("PJ_QRWF not in", values, "pjQrwf");
            return (Criteria) this;
        }

        public Criteria andPjQrwfBetween(Integer value1, Integer value2) {
            addCriterion("PJ_QRWF between", value1, value2, "pjQrwf");
            return (Criteria) this;
        }

        public Criteria andPjQrwfNotBetween(Integer value1, Integer value2) {
            addCriterion("PJ_QRWF not between", value1, value2, "pjQrwf");
            return (Criteria) this;
        }

        public Criteria andPjBhIsNull() {
            addCriterion("PJ_BH is null");
            return (Criteria) this;
        }

        public Criteria andPjBhIsNotNull() {
            addCriterion("PJ_BH is not null");
            return (Criteria) this;
        }

        public Criteria andPjBhEqualTo(Integer value) {
            addCriterion("PJ_BH =", value, "pjBh");
            return (Criteria) this;
        }

        public Criteria andPjBhNotEqualTo(Integer value) {
            addCriterion("PJ_BH <>", value, "pjBh");
            return (Criteria) this;
        }

        public Criteria andPjBhGreaterThan(Integer value) {
            addCriterion("PJ_BH >", value, "pjBh");
            return (Criteria) this;
        }

        public Criteria andPjBhGreaterThanOrEqualTo(Integer value) {
            addCriterion("PJ_BH >=", value, "pjBh");
            return (Criteria) this;
        }

        public Criteria andPjBhLessThan(Integer value) {
            addCriterion("PJ_BH <", value, "pjBh");
            return (Criteria) this;
        }

        public Criteria andPjBhLessThanOrEqualTo(Integer value) {
            addCriterion("PJ_BH <=", value, "pjBh");
            return (Criteria) this;
        }

        public Criteria andPjBhIn(List<Integer> values) {
            addCriterion("PJ_BH in", values, "pjBh");
            return (Criteria) this;
        }

        public Criteria andPjBhNotIn(List<Integer> values) {
            addCriterion("PJ_BH not in", values, "pjBh");
            return (Criteria) this;
        }

        public Criteria andPjBhBetween(Integer value1, Integer value2) {
            addCriterion("PJ_BH between", value1, value2, "pjBh");
            return (Criteria) this;
        }

        public Criteria andPjBhNotBetween(Integer value1, Integer value2) {
            addCriterion("PJ_BH not between", value1, value2, "pjBh");
            return (Criteria) this;
        }

        public Criteria andPjPcIsNull() {
            addCriterion("PJ_PC is null");
            return (Criteria) this;
        }

        public Criteria andPjPcIsNotNull() {
            addCriterion("PJ_PC is not null");
            return (Criteria) this;
        }

        public Criteria andPjPcEqualTo(Integer value) {
            addCriterion("PJ_PC =", value, "pjPc");
            return (Criteria) this;
        }

        public Criteria andPjPcNotEqualTo(Integer value) {
            addCriterion("PJ_PC <>", value, "pjPc");
            return (Criteria) this;
        }

        public Criteria andPjPcGreaterThan(Integer value) {
            addCriterion("PJ_PC >", value, "pjPc");
            return (Criteria) this;
        }

        public Criteria andPjPcGreaterThanOrEqualTo(Integer value) {
            addCriterion("PJ_PC >=", value, "pjPc");
            return (Criteria) this;
        }

        public Criteria andPjPcLessThan(Integer value) {
            addCriterion("PJ_PC <", value, "pjPc");
            return (Criteria) this;
        }

        public Criteria andPjPcLessThanOrEqualTo(Integer value) {
            addCriterion("PJ_PC <=", value, "pjPc");
            return (Criteria) this;
        }

        public Criteria andPjPcIn(List<Integer> values) {
            addCriterion("PJ_PC in", values, "pjPc");
            return (Criteria) this;
        }

        public Criteria andPjPcNotIn(List<Integer> values) {
            addCriterion("PJ_PC not in", values, "pjPc");
            return (Criteria) this;
        }

        public Criteria andPjPcBetween(Integer value1, Integer value2) {
            addCriterion("PJ_PC between", value1, value2, "pjPc");
            return (Criteria) this;
        }

        public Criteria andPjPcNotBetween(Integer value1, Integer value2) {
            addCriterion("PJ_PC not between", value1, value2, "pjPc");
            return (Criteria) this;
        }

        public Criteria andPjBypcIsNull() {
            addCriterion("PJ_BYPC is null");
            return (Criteria) this;
        }

        public Criteria andPjBypcIsNotNull() {
            addCriterion("PJ_BYPC is not null");
            return (Criteria) this;
        }

        public Criteria andPjBypcEqualTo(Integer value) {
            addCriterion("PJ_BYPC =", value, "pjBypc");
            return (Criteria) this;
        }

        public Criteria andPjBypcNotEqualTo(Integer value) {
            addCriterion("PJ_BYPC <>", value, "pjBypc");
            return (Criteria) this;
        }

        public Criteria andPjBypcGreaterThan(Integer value) {
            addCriterion("PJ_BYPC >", value, "pjBypc");
            return (Criteria) this;
        }

        public Criteria andPjBypcGreaterThanOrEqualTo(Integer value) {
            addCriterion("PJ_BYPC >=", value, "pjBypc");
            return (Criteria) this;
        }

        public Criteria andPjBypcLessThan(Integer value) {
            addCriterion("PJ_BYPC <", value, "pjBypc");
            return (Criteria) this;
        }

        public Criteria andPjBypcLessThanOrEqualTo(Integer value) {
            addCriterion("PJ_BYPC <=", value, "pjBypc");
            return (Criteria) this;
        }

        public Criteria andPjBypcIn(List<Integer> values) {
            addCriterion("PJ_BYPC in", values, "pjBypc");
            return (Criteria) this;
        }

        public Criteria andPjBypcNotIn(List<Integer> values) {
            addCriterion("PJ_BYPC not in", values, "pjBypc");
            return (Criteria) this;
        }

        public Criteria andPjBypcBetween(Integer value1, Integer value2) {
            addCriterion("PJ_BYPC between", value1, value2, "pjBypc");
            return (Criteria) this;
        }

        public Criteria andPjBypcNotBetween(Integer value1, Integer value2) {
            addCriterion("PJ_BYPC not between", value1, value2, "pjBypc");
            return (Criteria) this;
        }

        public Criteria andCdBhIsNull() {
            addCriterion("CD_BH is null");
            return (Criteria) this;
        }

        public Criteria andCdBhIsNotNull() {
            addCriterion("CD_BH is not null");
            return (Criteria) this;
        }

        public Criteria andCdBhEqualTo(Integer value) {
            addCriterion("CD_BH =", value, "cdBh");
            return (Criteria) this;
        }

        public Criteria andCdBhNotEqualTo(Integer value) {
            addCriterion("CD_BH <>", value, "cdBh");
            return (Criteria) this;
        }

        public Criteria andCdBhGreaterThan(Integer value) {
            addCriterion("CD_BH >", value, "cdBh");
            return (Criteria) this;
        }

        public Criteria andCdBhGreaterThanOrEqualTo(Integer value) {
            addCriterion("CD_BH >=", value, "cdBh");
            return (Criteria) this;
        }

        public Criteria andCdBhLessThan(Integer value) {
            addCriterion("CD_BH <", value, "cdBh");
            return (Criteria) this;
        }

        public Criteria andCdBhLessThanOrEqualTo(Integer value) {
            addCriterion("CD_BH <=", value, "cdBh");
            return (Criteria) this;
        }

        public Criteria andCdBhIn(List<Integer> values) {
            addCriterion("CD_BH in", values, "cdBh");
            return (Criteria) this;
        }

        public Criteria andCdBhNotIn(List<Integer> values) {
            addCriterion("CD_BH not in", values, "cdBh");
            return (Criteria) this;
        }

        public Criteria andCdBhBetween(Integer value1, Integer value2) {
            addCriterion("CD_BH between", value1, value2, "cdBh");
            return (Criteria) this;
        }

        public Criteria andCdBhNotBetween(Integer value1, Integer value2) {
            addCriterion("CD_BH not between", value1, value2, "cdBh");
            return (Criteria) this;
        }

        public Criteria andCdCsZdIsNull() {
            addCriterion("CD_CS_ZD is null");
            return (Criteria) this;
        }

        public Criteria andCdCsZdIsNotNull() {
            addCriterion("CD_CS_ZD is not null");
            return (Criteria) this;
        }

        public Criteria andCdCsZdEqualTo(Integer value) {
            addCriterion("CD_CS_ZD =", value, "cdCsZd");
            return (Criteria) this;
        }

        public Criteria andCdCsZdNotEqualTo(Integer value) {
            addCriterion("CD_CS_ZD <>", value, "cdCsZd");
            return (Criteria) this;
        }

        public Criteria andCdCsZdGreaterThan(Integer value) {
            addCriterion("CD_CS_ZD >", value, "cdCsZd");
            return (Criteria) this;
        }

        public Criteria andCdCsZdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CD_CS_ZD >=", value, "cdCsZd");
            return (Criteria) this;
        }

        public Criteria andCdCsZdLessThan(Integer value) {
            addCriterion("CD_CS_ZD <", value, "cdCsZd");
            return (Criteria) this;
        }

        public Criteria andCdCsZdLessThanOrEqualTo(Integer value) {
            addCriterion("CD_CS_ZD <=", value, "cdCsZd");
            return (Criteria) this;
        }

        public Criteria andCdCsZdIn(List<Integer> values) {
            addCriterion("CD_CS_ZD in", values, "cdCsZd");
            return (Criteria) this;
        }

        public Criteria andCdCsZdNotIn(List<Integer> values) {
            addCriterion("CD_CS_ZD not in", values, "cdCsZd");
            return (Criteria) this;
        }

        public Criteria andCdCsZdBetween(Integer value1, Integer value2) {
            addCriterion("CD_CS_ZD between", value1, value2, "cdCsZd");
            return (Criteria) this;
        }

        public Criteria andCdCsZdNotBetween(Integer value1, Integer value2) {
            addCriterion("CD_CS_ZD not between", value1, value2, "cdCsZd");
            return (Criteria) this;
        }

        public Criteria andCdCsGbIsNull() {
            addCriterion("CD_CS_GB is null");
            return (Criteria) this;
        }

        public Criteria andCdCsGbIsNotNull() {
            addCriterion("CD_CS_GB is not null");
            return (Criteria) this;
        }

        public Criteria andCdCsGbEqualTo(Integer value) {
            addCriterion("CD_CS_GB =", value, "cdCsGb");
            return (Criteria) this;
        }

        public Criteria andCdCsGbNotEqualTo(Integer value) {
            addCriterion("CD_CS_GB <>", value, "cdCsGb");
            return (Criteria) this;
        }

        public Criteria andCdCsGbGreaterThan(Integer value) {
            addCriterion("CD_CS_GB >", value, "cdCsGb");
            return (Criteria) this;
        }

        public Criteria andCdCsGbGreaterThanOrEqualTo(Integer value) {
            addCriterion("CD_CS_GB >=", value, "cdCsGb");
            return (Criteria) this;
        }

        public Criteria andCdCsGbLessThan(Integer value) {
            addCriterion("CD_CS_GB <", value, "cdCsGb");
            return (Criteria) this;
        }

        public Criteria andCdCsGbLessThanOrEqualTo(Integer value) {
            addCriterion("CD_CS_GB <=", value, "cdCsGb");
            return (Criteria) this;
        }

        public Criteria andCdCsGbIn(List<Integer> values) {
            addCriterion("CD_CS_GB in", values, "cdCsGb");
            return (Criteria) this;
        }

        public Criteria andCdCsGbNotIn(List<Integer> values) {
            addCriterion("CD_CS_GB not in", values, "cdCsGb");
            return (Criteria) this;
        }

        public Criteria andCdCsGbBetween(Integer value1, Integer value2) {
            addCriterion("CD_CS_GB between", value1, value2, "cdCsGb");
            return (Criteria) this;
        }

        public Criteria andCdCsGbNotBetween(Integer value1, Integer value2) {
            addCriterion("CD_CS_GB not between", value1, value2, "cdCsGb");
            return (Criteria) this;
        }

        public Criteria andCdYsIsNull() {
            addCriterion("CD_YS is null");
            return (Criteria) this;
        }

        public Criteria andCdYsIsNotNull() {
            addCriterion("CD_YS is not null");
            return (Criteria) this;
        }

        public Criteria andCdYsEqualTo(Integer value) {
            addCriterion("CD_YS =", value, "cdYs");
            return (Criteria) this;
        }

        public Criteria andCdYsNotEqualTo(Integer value) {
            addCriterion("CD_YS <>", value, "cdYs");
            return (Criteria) this;
        }

        public Criteria andCdYsGreaterThan(Integer value) {
            addCriterion("CD_YS >", value, "cdYs");
            return (Criteria) this;
        }

        public Criteria andCdYsGreaterThanOrEqualTo(Integer value) {
            addCriterion("CD_YS >=", value, "cdYs");
            return (Criteria) this;
        }

        public Criteria andCdYsLessThan(Integer value) {
            addCriterion("CD_YS <", value, "cdYs");
            return (Criteria) this;
        }

        public Criteria andCdYsLessThanOrEqualTo(Integer value) {
            addCriterion("CD_YS <=", value, "cdYs");
            return (Criteria) this;
        }

        public Criteria andCdYsIn(List<Integer> values) {
            addCriterion("CD_YS in", values, "cdYs");
            return (Criteria) this;
        }

        public Criteria andCdYsNotIn(List<Integer> values) {
            addCriterion("CD_YS not in", values, "cdYs");
            return (Criteria) this;
        }

        public Criteria andCdYsBetween(Integer value1, Integer value2) {
            addCriterion("CD_YS between", value1, value2, "cdYs");
            return (Criteria) this;
        }

        public Criteria andCdYsNotBetween(Integer value1, Integer value2) {
            addCriterion("CD_YS not between", value1, value2, "cdYs");
            return (Criteria) this;
        }

        public Criteria andCdZjIsNull() {
            addCriterion("CD_ZJ is null");
            return (Criteria) this;
        }

        public Criteria andCdZjIsNotNull() {
            addCriterion("CD_ZJ is not null");
            return (Criteria) this;
        }

        public Criteria andCdZjEqualTo(Integer value) {
            addCriterion("CD_ZJ =", value, "cdZj");
            return (Criteria) this;
        }

        public Criteria andCdZjNotEqualTo(Integer value) {
            addCriterion("CD_ZJ <>", value, "cdZj");
            return (Criteria) this;
        }

        public Criteria andCdZjGreaterThan(Integer value) {
            addCriterion("CD_ZJ >", value, "cdZj");
            return (Criteria) this;
        }

        public Criteria andCdZjGreaterThanOrEqualTo(Integer value) {
            addCriterion("CD_ZJ >=", value, "cdZj");
            return (Criteria) this;
        }

        public Criteria andCdZjLessThan(Integer value) {
            addCriterion("CD_ZJ <", value, "cdZj");
            return (Criteria) this;
        }

        public Criteria andCdZjLessThanOrEqualTo(Integer value) {
            addCriterion("CD_ZJ <=", value, "cdZj");
            return (Criteria) this;
        }

        public Criteria andCdZjIn(List<Integer> values) {
            addCriterion("CD_ZJ in", values, "cdZj");
            return (Criteria) this;
        }

        public Criteria andCdZjNotIn(List<Integer> values) {
            addCriterion("CD_ZJ not in", values, "cdZj");
            return (Criteria) this;
        }

        public Criteria andCdZjBetween(Integer value1, Integer value2) {
            addCriterion("CD_ZJ between", value1, value2, "cdZj");
            return (Criteria) this;
        }

        public Criteria andCdZjNotBetween(Integer value1, Integer value2) {
            addCriterion("CD_ZJ not between", value1, value2, "cdZj");
            return (Criteria) this;
        }

        public Criteria andCdQtIsNull() {
            addCriterion("CD_QT is null");
            return (Criteria) this;
        }

        public Criteria andCdQtIsNotNull() {
            addCriterion("CD_QT is not null");
            return (Criteria) this;
        }

        public Criteria andCdQtEqualTo(Integer value) {
            addCriterion("CD_QT =", value, "cdQt");
            return (Criteria) this;
        }

        public Criteria andCdQtNotEqualTo(Integer value) {
            addCriterion("CD_QT <>", value, "cdQt");
            return (Criteria) this;
        }

        public Criteria andCdQtGreaterThan(Integer value) {
            addCriterion("CD_QT >", value, "cdQt");
            return (Criteria) this;
        }

        public Criteria andCdQtGreaterThanOrEqualTo(Integer value) {
            addCriterion("CD_QT >=", value, "cdQt");
            return (Criteria) this;
        }

        public Criteria andCdQtLessThan(Integer value) {
            addCriterion("CD_QT <", value, "cdQt");
            return (Criteria) this;
        }

        public Criteria andCdQtLessThanOrEqualTo(Integer value) {
            addCriterion("CD_QT <=", value, "cdQt");
            return (Criteria) this;
        }

        public Criteria andCdQtIn(List<Integer> values) {
            addCriterion("CD_QT in", values, "cdQt");
            return (Criteria) this;
        }

        public Criteria andCdQtNotIn(List<Integer> values) {
            addCriterion("CD_QT not in", values, "cdQt");
            return (Criteria) this;
        }

        public Criteria andCdQtBetween(Integer value1, Integer value2) {
            addCriterion("CD_QT between", value1, value2, "cdQt");
            return (Criteria) this;
        }

        public Criteria andCdQtNotBetween(Integer value1, Integer value2) {
            addCriterion("CD_QT not between", value1, value2, "cdQt");
            return (Criteria) this;
        }

        public Criteria andYsjaPctjIsNull() {
            addCriterion("YSJA_PCTJ is null");
            return (Criteria) this;
        }

        public Criteria andYsjaPctjIsNotNull() {
            addCriterion("YSJA_PCTJ is not null");
            return (Criteria) this;
        }

        public Criteria andYsjaPctjEqualTo(Integer value) {
            addCriterion("YSJA_PCTJ =", value, "ysjaPctj");
            return (Criteria) this;
        }

        public Criteria andYsjaPctjNotEqualTo(Integer value) {
            addCriterion("YSJA_PCTJ <>", value, "ysjaPctj");
            return (Criteria) this;
        }

        public Criteria andYsjaPctjGreaterThan(Integer value) {
            addCriterion("YSJA_PCTJ >", value, "ysjaPctj");
            return (Criteria) this;
        }

        public Criteria andYsjaPctjGreaterThanOrEqualTo(Integer value) {
            addCriterion("YSJA_PCTJ >=", value, "ysjaPctj");
            return (Criteria) this;
        }

        public Criteria andYsjaPctjLessThan(Integer value) {
            addCriterion("YSJA_PCTJ <", value, "ysjaPctj");
            return (Criteria) this;
        }

        public Criteria andYsjaPctjLessThanOrEqualTo(Integer value) {
            addCriterion("YSJA_PCTJ <=", value, "ysjaPctj");
            return (Criteria) this;
        }

        public Criteria andYsjaPctjIn(List<Integer> values) {
            addCriterion("YSJA_PCTJ in", values, "ysjaPctj");
            return (Criteria) this;
        }

        public Criteria andYsjaPctjNotIn(List<Integer> values) {
            addCriterion("YSJA_PCTJ not in", values, "ysjaPctj");
            return (Criteria) this;
        }

        public Criteria andYsjaPctjBetween(Integer value1, Integer value2) {
            addCriterion("YSJA_PCTJ between", value1, value2, "ysjaPctj");
            return (Criteria) this;
        }

        public Criteria andYsjaPctjNotBetween(Integer value1, Integer value2) {
            addCriterion("YSJA_PCTJ not between", value1, value2, "ysjaPctj");
            return (Criteria) this;
        }

        public Criteria andWsjIsNull() {
            addCriterion("WSJ is null");
            return (Criteria) this;
        }

        public Criteria andWsjIsNotNull() {
            addCriterion("WSJ is not null");
            return (Criteria) this;
        }

        public Criteria andWsjEqualTo(Integer value) {
            addCriterion("WSJ =", value, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjNotEqualTo(Integer value) {
            addCriterion("WSJ <>", value, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjGreaterThan(Integer value) {
            addCriterion("WSJ >", value, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjGreaterThanOrEqualTo(Integer value) {
            addCriterion("WSJ >=", value, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjLessThan(Integer value) {
            addCriterion("WSJ <", value, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjLessThanOrEqualTo(Integer value) {
            addCriterion("WSJ <=", value, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjIn(List<Integer> values) {
            addCriterion("WSJ in", values, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjNotIn(List<Integer> values) {
            addCriterion("WSJ not in", values, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjBetween(Integer value1, Integer value2) {
            addCriterion("WSJ between", value1, value2, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjNotBetween(Integer value1, Integer value2) {
            addCriterion("WSJ not between", value1, value2, "wsj");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("Province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("Province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("Province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("Province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("Province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("Province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("Province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("Province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("Province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("Province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("Province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("Province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("Province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("Province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("Year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("Year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(Integer value) {
            addCriterion("Year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(Integer value) {
            addCriterion("Year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(Integer value) {
            addCriterion("Year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("Year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(Integer value) {
            addCriterion("Year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(Integer value) {
            addCriterion("Year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<Integer> values) {
            addCriterion("Year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<Integer> values) {
            addCriterion("Year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(Integer value1, Integer value2) {
            addCriterion("Year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(Integer value1, Integer value2) {
            addCriterion("Year not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andSeqnoIsNull() {
            addCriterion("SeqNo is null");
            return (Criteria) this;
        }

        public Criteria andSeqnoIsNotNull() {
            addCriterion("SeqNo is not null");
            return (Criteria) this;
        }

        public Criteria andSeqnoEqualTo(Integer value) {
            addCriterion("SeqNo =", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotEqualTo(Integer value) {
            addCriterion("SeqNo <>", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoGreaterThan(Integer value) {
            addCriterion("SeqNo >", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("SeqNo >=", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLessThan(Integer value) {
            addCriterion("SeqNo <", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLessThanOrEqualTo(Integer value) {
            addCriterion("SeqNo <=", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoIn(List<Integer> values) {
            addCriterion("SeqNo in", values, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotIn(List<Integer> values) {
            addCriterion("SeqNo not in", values, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoBetween(Integer value1, Integer value2) {
            addCriterion("SeqNo between", value1, value2, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotBetween(Integer value1, Integer value2) {
            addCriterion("SeqNo not between", value1, value2, "seqno");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adminresponsecase
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 19 01:33:39 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adminresponsecase
     *
     * @mbggenerated Thu Jul 19 01:33:39 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}