package com.ejunhai.qutihuo.statistical.model;

public class Fixedassetsandcapitalconstruction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.ID
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.ZCCNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer zccnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.FIXEDASSETSCNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer fixedassetscnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.FA_FWJZW
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer faFwjzw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.FA_FWJZW_BNXZ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer faFwjzwBnxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.FA_JTYSSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer faJtyssb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.FA_JTYSSB_BNXZ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer faJtyssbBnxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_CNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer faZyyqsbCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_JLYQZYSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer faZyyqsbJlyqzysb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_TZSBJYYQZYSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer faZyyqsbTzsbjyyqzysb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_CNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer faZyyqsbBnxzCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_JLYQZYSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer faZyyqsbBnxzJlyqzysb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_TZSBJYYQZYSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer faZyyqsbBnxzTzsbjyyqzysb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.FA_OTHER
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer faOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.B_CNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer bCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.B_SYSMJ_CNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer bSysmjCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.B_JYSYSMJ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer bJysysmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.B_TZSBSYSMJ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer bTzsbsysmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.B_BGYFMJ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer bBgyfmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.B_OTHER
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer bOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.CC_BNZJXM
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer ccBnzjxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.CC_BNTZJE
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer ccBntzje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.CC_BNZJJZMJ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer ccBnzjjzmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.YEAR
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.PROVINCE
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixedassetsandcapitalconstruction.SEQNO
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    private Integer seqno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.ID
     *
     * @return the value of fixedassetsandcapitalconstruction.ID
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.ID
     *
     * @param id the value for fixedassetsandcapitalconstruction.ID
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.ZCCNT
     *
     * @return the value of fixedassetsandcapitalconstruction.ZCCNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getZccnt() {
        return zccnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.ZCCNT
     *
     * @param zccnt the value for fixedassetsandcapitalconstruction.ZCCNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setZccnt(Integer zccnt) {
        this.zccnt = zccnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.FIXEDASSETSCNT
     *
     * @return the value of fixedassetsandcapitalconstruction.FIXEDASSETSCNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getFixedassetscnt() {
        return fixedassetscnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.FIXEDASSETSCNT
     *
     * @param fixedassetscnt the value for fixedassetsandcapitalconstruction.FIXEDASSETSCNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setFixedassetscnt(Integer fixedassetscnt) {
        this.fixedassetscnt = fixedassetscnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.FA_FWJZW
     *
     * @return the value of fixedassetsandcapitalconstruction.FA_FWJZW
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getFaFwjzw() {
        return faFwjzw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.FA_FWJZW
     *
     * @param faFwjzw the value for fixedassetsandcapitalconstruction.FA_FWJZW
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setFaFwjzw(Integer faFwjzw) {
        this.faFwjzw = faFwjzw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.FA_FWJZW_BNXZ
     *
     * @return the value of fixedassetsandcapitalconstruction.FA_FWJZW_BNXZ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getFaFwjzwBnxz() {
        return faFwjzwBnxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.FA_FWJZW_BNXZ
     *
     * @param faFwjzwBnxz the value for fixedassetsandcapitalconstruction.FA_FWJZW_BNXZ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setFaFwjzwBnxz(Integer faFwjzwBnxz) {
        this.faFwjzwBnxz = faFwjzwBnxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.FA_JTYSSB
     *
     * @return the value of fixedassetsandcapitalconstruction.FA_JTYSSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getFaJtyssb() {
        return faJtyssb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.FA_JTYSSB
     *
     * @param faJtyssb the value for fixedassetsandcapitalconstruction.FA_JTYSSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setFaJtyssb(Integer faJtyssb) {
        this.faJtyssb = faJtyssb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.FA_JTYSSB_BNXZ
     *
     * @return the value of fixedassetsandcapitalconstruction.FA_JTYSSB_BNXZ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getFaJtyssbBnxz() {
        return faJtyssbBnxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.FA_JTYSSB_BNXZ
     *
     * @param faJtyssbBnxz the value for fixedassetsandcapitalconstruction.FA_JTYSSB_BNXZ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setFaJtyssbBnxz(Integer faJtyssbBnxz) {
        this.faJtyssbBnxz = faJtyssbBnxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_CNT
     *
     * @return the value of fixedassetsandcapitalconstruction.FA_ZYYQSB_CNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getFaZyyqsbCnt() {
        return faZyyqsbCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_CNT
     *
     * @param faZyyqsbCnt the value for fixedassetsandcapitalconstruction.FA_ZYYQSB_CNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setFaZyyqsbCnt(Integer faZyyqsbCnt) {
        this.faZyyqsbCnt = faZyyqsbCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_JLYQZYSB
     *
     * @return the value of fixedassetsandcapitalconstruction.FA_ZYYQSB_JLYQZYSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getFaZyyqsbJlyqzysb() {
        return faZyyqsbJlyqzysb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_JLYQZYSB
     *
     * @param faZyyqsbJlyqzysb the value for fixedassetsandcapitalconstruction.FA_ZYYQSB_JLYQZYSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setFaZyyqsbJlyqzysb(Integer faZyyqsbJlyqzysb) {
        this.faZyyqsbJlyqzysb = faZyyqsbJlyqzysb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_TZSBJYYQZYSB
     *
     * @return the value of fixedassetsandcapitalconstruction.FA_ZYYQSB_TZSBJYYQZYSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getFaZyyqsbTzsbjyyqzysb() {
        return faZyyqsbTzsbjyyqzysb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_TZSBJYYQZYSB
     *
     * @param faZyyqsbTzsbjyyqzysb the value for fixedassetsandcapitalconstruction.FA_ZYYQSB_TZSBJYYQZYSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setFaZyyqsbTzsbjyyqzysb(Integer faZyyqsbTzsbjyyqzysb) {
        this.faZyyqsbTzsbjyyqzysb = faZyyqsbTzsbjyyqzysb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_CNT
     *
     * @return the value of fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_CNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getFaZyyqsbBnxzCnt() {
        return faZyyqsbBnxzCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_CNT
     *
     * @param faZyyqsbBnxzCnt the value for fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_CNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setFaZyyqsbBnxzCnt(Integer faZyyqsbBnxzCnt) {
        this.faZyyqsbBnxzCnt = faZyyqsbBnxzCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_JLYQZYSB
     *
     * @return the value of fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_JLYQZYSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getFaZyyqsbBnxzJlyqzysb() {
        return faZyyqsbBnxzJlyqzysb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_JLYQZYSB
     *
     * @param faZyyqsbBnxzJlyqzysb the value for fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_JLYQZYSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setFaZyyqsbBnxzJlyqzysb(Integer faZyyqsbBnxzJlyqzysb) {
        this.faZyyqsbBnxzJlyqzysb = faZyyqsbBnxzJlyqzysb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_TZSBJYYQZYSB
     *
     * @return the value of fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_TZSBJYYQZYSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getFaZyyqsbBnxzTzsbjyyqzysb() {
        return faZyyqsbBnxzTzsbjyyqzysb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_TZSBJYYQZYSB
     *
     * @param faZyyqsbBnxzTzsbjyyqzysb the value for fixedassetsandcapitalconstruction.FA_ZYYQSB_BNXZ_TZSBJYYQZYSB
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setFaZyyqsbBnxzTzsbjyyqzysb(Integer faZyyqsbBnxzTzsbjyyqzysb) {
        this.faZyyqsbBnxzTzsbjyyqzysb = faZyyqsbBnxzTzsbjyyqzysb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.FA_OTHER
     *
     * @return the value of fixedassetsandcapitalconstruction.FA_OTHER
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getFaOther() {
        return faOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.FA_OTHER
     *
     * @param faOther the value for fixedassetsandcapitalconstruction.FA_OTHER
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setFaOther(Integer faOther) {
        this.faOther = faOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.B_CNT
     *
     * @return the value of fixedassetsandcapitalconstruction.B_CNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getbCnt() {
        return bCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.B_CNT
     *
     * @param bCnt the value for fixedassetsandcapitalconstruction.B_CNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setbCnt(Integer bCnt) {
        this.bCnt = bCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.B_SYSMJ_CNT
     *
     * @return the value of fixedassetsandcapitalconstruction.B_SYSMJ_CNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getbSysmjCnt() {
        return bSysmjCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.B_SYSMJ_CNT
     *
     * @param bSysmjCnt the value for fixedassetsandcapitalconstruction.B_SYSMJ_CNT
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setbSysmjCnt(Integer bSysmjCnt) {
        this.bSysmjCnt = bSysmjCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.B_JYSYSMJ
     *
     * @return the value of fixedassetsandcapitalconstruction.B_JYSYSMJ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getbJysysmj() {
        return bJysysmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.B_JYSYSMJ
     *
     * @param bJysysmj the value for fixedassetsandcapitalconstruction.B_JYSYSMJ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setbJysysmj(Integer bJysysmj) {
        this.bJysysmj = bJysysmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.B_TZSBSYSMJ
     *
     * @return the value of fixedassetsandcapitalconstruction.B_TZSBSYSMJ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getbTzsbsysmj() {
        return bTzsbsysmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.B_TZSBSYSMJ
     *
     * @param bTzsbsysmj the value for fixedassetsandcapitalconstruction.B_TZSBSYSMJ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setbTzsbsysmj(Integer bTzsbsysmj) {
        this.bTzsbsysmj = bTzsbsysmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.B_BGYFMJ
     *
     * @return the value of fixedassetsandcapitalconstruction.B_BGYFMJ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getbBgyfmj() {
        return bBgyfmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.B_BGYFMJ
     *
     * @param bBgyfmj the value for fixedassetsandcapitalconstruction.B_BGYFMJ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setbBgyfmj(Integer bBgyfmj) {
        this.bBgyfmj = bBgyfmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.B_OTHER
     *
     * @return the value of fixedassetsandcapitalconstruction.B_OTHER
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getbOther() {
        return bOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.B_OTHER
     *
     * @param bOther the value for fixedassetsandcapitalconstruction.B_OTHER
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setbOther(Integer bOther) {
        this.bOther = bOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.CC_BNZJXM
     *
     * @return the value of fixedassetsandcapitalconstruction.CC_BNZJXM
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getCcBnzjxm() {
        return ccBnzjxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.CC_BNZJXM
     *
     * @param ccBnzjxm the value for fixedassetsandcapitalconstruction.CC_BNZJXM
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setCcBnzjxm(Integer ccBnzjxm) {
        this.ccBnzjxm = ccBnzjxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.CC_BNTZJE
     *
     * @return the value of fixedassetsandcapitalconstruction.CC_BNTZJE
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getCcBntzje() {
        return ccBntzje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.CC_BNTZJE
     *
     * @param ccBntzje the value for fixedassetsandcapitalconstruction.CC_BNTZJE
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setCcBntzje(Integer ccBntzje) {
        this.ccBntzje = ccBntzje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.CC_BNZJJZMJ
     *
     * @return the value of fixedassetsandcapitalconstruction.CC_BNZJJZMJ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getCcBnzjjzmj() {
        return ccBnzjjzmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.CC_BNZJJZMJ
     *
     * @param ccBnzjjzmj the value for fixedassetsandcapitalconstruction.CC_BNZJJZMJ
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setCcBnzjjzmj(Integer ccBnzjjzmj) {
        this.ccBnzjjzmj = ccBnzjjzmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.YEAR
     *
     * @return the value of fixedassetsandcapitalconstruction.YEAR
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.YEAR
     *
     * @param year the value for fixedassetsandcapitalconstruction.YEAR
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.PROVINCE
     *
     * @return the value of fixedassetsandcapitalconstruction.PROVINCE
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.PROVINCE
     *
     * @param province the value for fixedassetsandcapitalconstruction.PROVINCE
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixedassetsandcapitalconstruction.SEQNO
     *
     * @return the value of fixedassetsandcapitalconstruction.SEQNO
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Integer getSeqno() {
        return seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixedassetsandcapitalconstruction.SEQNO
     *
     * @param seqno the value for fixedassetsandcapitalconstruction.SEQNO
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setSeqno(Integer seqno) {
        this.seqno = seqno;
    }
}