package com.ejunhai.qutihuo.statistical.model;

import java.util.ArrayList;
import java.util.List;

public class FixedassetsandcapitalconstructionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public FixedassetsandcapitalconstructionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andZccntIsNull() {
            addCriterion("ZCCNT is null");
            return (Criteria) this;
        }

        public Criteria andZccntIsNotNull() {
            addCriterion("ZCCNT is not null");
            return (Criteria) this;
        }

        public Criteria andZccntEqualTo(Integer value) {
            addCriterion("ZCCNT =", value, "zccnt");
            return (Criteria) this;
        }

        public Criteria andZccntNotEqualTo(Integer value) {
            addCriterion("ZCCNT <>", value, "zccnt");
            return (Criteria) this;
        }

        public Criteria andZccntGreaterThan(Integer value) {
            addCriterion("ZCCNT >", value, "zccnt");
            return (Criteria) this;
        }

        public Criteria andZccntGreaterThanOrEqualTo(Integer value) {
            addCriterion("ZCCNT >=", value, "zccnt");
            return (Criteria) this;
        }

        public Criteria andZccntLessThan(Integer value) {
            addCriterion("ZCCNT <", value, "zccnt");
            return (Criteria) this;
        }

        public Criteria andZccntLessThanOrEqualTo(Integer value) {
            addCriterion("ZCCNT <=", value, "zccnt");
            return (Criteria) this;
        }

        public Criteria andZccntIn(List<Integer> values) {
            addCriterion("ZCCNT in", values, "zccnt");
            return (Criteria) this;
        }

        public Criteria andZccntNotIn(List<Integer> values) {
            addCriterion("ZCCNT not in", values, "zccnt");
            return (Criteria) this;
        }

        public Criteria andZccntBetween(Integer value1, Integer value2) {
            addCriterion("ZCCNT between", value1, value2, "zccnt");
            return (Criteria) this;
        }

        public Criteria andZccntNotBetween(Integer value1, Integer value2) {
            addCriterion("ZCCNT not between", value1, value2, "zccnt");
            return (Criteria) this;
        }

        public Criteria andFixedassetscntIsNull() {
            addCriterion("FIXEDASSETSCNT is null");
            return (Criteria) this;
        }

        public Criteria andFixedassetscntIsNotNull() {
            addCriterion("FIXEDASSETSCNT is not null");
            return (Criteria) this;
        }

        public Criteria andFixedassetscntEqualTo(Integer value) {
            addCriterion("FIXEDASSETSCNT =", value, "fixedassetscnt");
            return (Criteria) this;
        }

        public Criteria andFixedassetscntNotEqualTo(Integer value) {
            addCriterion("FIXEDASSETSCNT <>", value, "fixedassetscnt");
            return (Criteria) this;
        }

        public Criteria andFixedassetscntGreaterThan(Integer value) {
            addCriterion("FIXEDASSETSCNT >", value, "fixedassetscnt");
            return (Criteria) this;
        }

        public Criteria andFixedassetscntGreaterThanOrEqualTo(Integer value) {
            addCriterion("FIXEDASSETSCNT >=", value, "fixedassetscnt");
            return (Criteria) this;
        }

        public Criteria andFixedassetscntLessThan(Integer value) {
            addCriterion("FIXEDASSETSCNT <", value, "fixedassetscnt");
            return (Criteria) this;
        }

        public Criteria andFixedassetscntLessThanOrEqualTo(Integer value) {
            addCriterion("FIXEDASSETSCNT <=", value, "fixedassetscnt");
            return (Criteria) this;
        }

        public Criteria andFixedassetscntIn(List<Integer> values) {
            addCriterion("FIXEDASSETSCNT in", values, "fixedassetscnt");
            return (Criteria) this;
        }

        public Criteria andFixedassetscntNotIn(List<Integer> values) {
            addCriterion("FIXEDASSETSCNT not in", values, "fixedassetscnt");
            return (Criteria) this;
        }

        public Criteria andFixedassetscntBetween(Integer value1, Integer value2) {
            addCriterion("FIXEDASSETSCNT between", value1, value2, "fixedassetscnt");
            return (Criteria) this;
        }

        public Criteria andFixedassetscntNotBetween(Integer value1, Integer value2) {
            addCriterion("FIXEDASSETSCNT not between", value1, value2, "fixedassetscnt");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwIsNull() {
            addCriterion("FA_FWJZW is null");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwIsNotNull() {
            addCriterion("FA_FWJZW is not null");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwEqualTo(Integer value) {
            addCriterion("FA_FWJZW =", value, "faFwjzw");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwNotEqualTo(Integer value) {
            addCriterion("FA_FWJZW <>", value, "faFwjzw");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwGreaterThan(Integer value) {
            addCriterion("FA_FWJZW >", value, "faFwjzw");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwGreaterThanOrEqualTo(Integer value) {
            addCriterion("FA_FWJZW >=", value, "faFwjzw");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwLessThan(Integer value) {
            addCriterion("FA_FWJZW <", value, "faFwjzw");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwLessThanOrEqualTo(Integer value) {
            addCriterion("FA_FWJZW <=", value, "faFwjzw");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwIn(List<Integer> values) {
            addCriterion("FA_FWJZW in", values, "faFwjzw");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwNotIn(List<Integer> values) {
            addCriterion("FA_FWJZW not in", values, "faFwjzw");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwBetween(Integer value1, Integer value2) {
            addCriterion("FA_FWJZW between", value1, value2, "faFwjzw");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwNotBetween(Integer value1, Integer value2) {
            addCriterion("FA_FWJZW not between", value1, value2, "faFwjzw");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwBnxzIsNull() {
            addCriterion("FA_FWJZW_BNXZ is null");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwBnxzIsNotNull() {
            addCriterion("FA_FWJZW_BNXZ is not null");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwBnxzEqualTo(Integer value) {
            addCriterion("FA_FWJZW_BNXZ =", value, "faFwjzwBnxz");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwBnxzNotEqualTo(Integer value) {
            addCriterion("FA_FWJZW_BNXZ <>", value, "faFwjzwBnxz");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwBnxzGreaterThan(Integer value) {
            addCriterion("FA_FWJZW_BNXZ >", value, "faFwjzwBnxz");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwBnxzGreaterThanOrEqualTo(Integer value) {
            addCriterion("FA_FWJZW_BNXZ >=", value, "faFwjzwBnxz");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwBnxzLessThan(Integer value) {
            addCriterion("FA_FWJZW_BNXZ <", value, "faFwjzwBnxz");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwBnxzLessThanOrEqualTo(Integer value) {
            addCriterion("FA_FWJZW_BNXZ <=", value, "faFwjzwBnxz");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwBnxzIn(List<Integer> values) {
            addCriterion("FA_FWJZW_BNXZ in", values, "faFwjzwBnxz");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwBnxzNotIn(List<Integer> values) {
            addCriterion("FA_FWJZW_BNXZ not in", values, "faFwjzwBnxz");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwBnxzBetween(Integer value1, Integer value2) {
            addCriterion("FA_FWJZW_BNXZ between", value1, value2, "faFwjzwBnxz");
            return (Criteria) this;
        }

        public Criteria andFaFwjzwBnxzNotBetween(Integer value1, Integer value2) {
            addCriterion("FA_FWJZW_BNXZ not between", value1, value2, "faFwjzwBnxz");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbIsNull() {
            addCriterion("FA_JTYSSB is null");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbIsNotNull() {
            addCriterion("FA_JTYSSB is not null");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbEqualTo(Integer value) {
            addCriterion("FA_JTYSSB =", value, "faJtyssb");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbNotEqualTo(Integer value) {
            addCriterion("FA_JTYSSB <>", value, "faJtyssb");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbGreaterThan(Integer value) {
            addCriterion("FA_JTYSSB >", value, "faJtyssb");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbGreaterThanOrEqualTo(Integer value) {
            addCriterion("FA_JTYSSB >=", value, "faJtyssb");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbLessThan(Integer value) {
            addCriterion("FA_JTYSSB <", value, "faJtyssb");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbLessThanOrEqualTo(Integer value) {
            addCriterion("FA_JTYSSB <=", value, "faJtyssb");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbIn(List<Integer> values) {
            addCriterion("FA_JTYSSB in", values, "faJtyssb");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbNotIn(List<Integer> values) {
            addCriterion("FA_JTYSSB not in", values, "faJtyssb");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbBetween(Integer value1, Integer value2) {
            addCriterion("FA_JTYSSB between", value1, value2, "faJtyssb");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbNotBetween(Integer value1, Integer value2) {
            addCriterion("FA_JTYSSB not between", value1, value2, "faJtyssb");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbBnxzIsNull() {
            addCriterion("FA_JTYSSB_BNXZ is null");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbBnxzIsNotNull() {
            addCriterion("FA_JTYSSB_BNXZ is not null");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbBnxzEqualTo(Integer value) {
            addCriterion("FA_JTYSSB_BNXZ =", value, "faJtyssbBnxz");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbBnxzNotEqualTo(Integer value) {
            addCriterion("FA_JTYSSB_BNXZ <>", value, "faJtyssbBnxz");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbBnxzGreaterThan(Integer value) {
            addCriterion("FA_JTYSSB_BNXZ >", value, "faJtyssbBnxz");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbBnxzGreaterThanOrEqualTo(Integer value) {
            addCriterion("FA_JTYSSB_BNXZ >=", value, "faJtyssbBnxz");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbBnxzLessThan(Integer value) {
            addCriterion("FA_JTYSSB_BNXZ <", value, "faJtyssbBnxz");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbBnxzLessThanOrEqualTo(Integer value) {
            addCriterion("FA_JTYSSB_BNXZ <=", value, "faJtyssbBnxz");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbBnxzIn(List<Integer> values) {
            addCriterion("FA_JTYSSB_BNXZ in", values, "faJtyssbBnxz");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbBnxzNotIn(List<Integer> values) {
            addCriterion("FA_JTYSSB_BNXZ not in", values, "faJtyssbBnxz");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbBnxzBetween(Integer value1, Integer value2) {
            addCriterion("FA_JTYSSB_BNXZ between", value1, value2, "faJtyssbBnxz");
            return (Criteria) this;
        }

        public Criteria andFaJtyssbBnxzNotBetween(Integer value1, Integer value2) {
            addCriterion("FA_JTYSSB_BNXZ not between", value1, value2, "faJtyssbBnxz");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbCntIsNull() {
            addCriterion("FA_ZYYQSB_CNT is null");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbCntIsNotNull() {
            addCriterion("FA_ZYYQSB_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbCntEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_CNT =", value, "faZyyqsbCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbCntNotEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_CNT <>", value, "faZyyqsbCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbCntGreaterThan(Integer value) {
            addCriterion("FA_ZYYQSB_CNT >", value, "faZyyqsbCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_CNT >=", value, "faZyyqsbCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbCntLessThan(Integer value) {
            addCriterion("FA_ZYYQSB_CNT <", value, "faZyyqsbCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbCntLessThanOrEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_CNT <=", value, "faZyyqsbCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbCntIn(List<Integer> values) {
            addCriterion("FA_ZYYQSB_CNT in", values, "faZyyqsbCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbCntNotIn(List<Integer> values) {
            addCriterion("FA_ZYYQSB_CNT not in", values, "faZyyqsbCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbCntBetween(Integer value1, Integer value2) {
            addCriterion("FA_ZYYQSB_CNT between", value1, value2, "faZyyqsbCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbCntNotBetween(Integer value1, Integer value2) {
            addCriterion("FA_ZYYQSB_CNT not between", value1, value2, "faZyyqsbCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbJlyqzysbIsNull() {
            addCriterion("FA_ZYYQSB_JLYQZYSB is null");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbJlyqzysbIsNotNull() {
            addCriterion("FA_ZYYQSB_JLYQZYSB is not null");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbJlyqzysbEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_JLYQZYSB =", value, "faZyyqsbJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbJlyqzysbNotEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_JLYQZYSB <>", value, "faZyyqsbJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbJlyqzysbGreaterThan(Integer value) {
            addCriterion("FA_ZYYQSB_JLYQZYSB >", value, "faZyyqsbJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbJlyqzysbGreaterThanOrEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_JLYQZYSB >=", value, "faZyyqsbJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbJlyqzysbLessThan(Integer value) {
            addCriterion("FA_ZYYQSB_JLYQZYSB <", value, "faZyyqsbJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbJlyqzysbLessThanOrEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_JLYQZYSB <=", value, "faZyyqsbJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbJlyqzysbIn(List<Integer> values) {
            addCriterion("FA_ZYYQSB_JLYQZYSB in", values, "faZyyqsbJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbJlyqzysbNotIn(List<Integer> values) {
            addCriterion("FA_ZYYQSB_JLYQZYSB not in", values, "faZyyqsbJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbJlyqzysbBetween(Integer value1, Integer value2) {
            addCriterion("FA_ZYYQSB_JLYQZYSB between", value1, value2, "faZyyqsbJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbJlyqzysbNotBetween(Integer value1, Integer value2) {
            addCriterion("FA_ZYYQSB_JLYQZYSB not between", value1, value2, "faZyyqsbJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbTzsbjyyqzysbIsNull() {
            addCriterion("FA_ZYYQSB_TZSBJYYQZYSB is null");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbTzsbjyyqzysbIsNotNull() {
            addCriterion("FA_ZYYQSB_TZSBJYYQZYSB is not null");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbTzsbjyyqzysbEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_TZSBJYYQZYSB =", value, "faZyyqsbTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbTzsbjyyqzysbNotEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_TZSBJYYQZYSB <>", value, "faZyyqsbTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbTzsbjyyqzysbGreaterThan(Integer value) {
            addCriterion("FA_ZYYQSB_TZSBJYYQZYSB >", value, "faZyyqsbTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbTzsbjyyqzysbGreaterThanOrEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_TZSBJYYQZYSB >=", value, "faZyyqsbTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbTzsbjyyqzysbLessThan(Integer value) {
            addCriterion("FA_ZYYQSB_TZSBJYYQZYSB <", value, "faZyyqsbTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbTzsbjyyqzysbLessThanOrEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_TZSBJYYQZYSB <=", value, "faZyyqsbTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbTzsbjyyqzysbIn(List<Integer> values) {
            addCriterion("FA_ZYYQSB_TZSBJYYQZYSB in", values, "faZyyqsbTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbTzsbjyyqzysbNotIn(List<Integer> values) {
            addCriterion("FA_ZYYQSB_TZSBJYYQZYSB not in", values, "faZyyqsbTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbTzsbjyyqzysbBetween(Integer value1, Integer value2) {
            addCriterion("FA_ZYYQSB_TZSBJYYQZYSB between", value1, value2, "faZyyqsbTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbTzsbjyyqzysbNotBetween(Integer value1, Integer value2) {
            addCriterion("FA_ZYYQSB_TZSBJYYQZYSB not between", value1, value2, "faZyyqsbTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzCntIsNull() {
            addCriterion("FA_ZYYQSB_BNXZ_CNT is null");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzCntIsNotNull() {
            addCriterion("FA_ZYYQSB_BNXZ_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzCntEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_CNT =", value, "faZyyqsbBnxzCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzCntNotEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_CNT <>", value, "faZyyqsbBnxzCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzCntGreaterThan(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_CNT >", value, "faZyyqsbBnxzCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_CNT >=", value, "faZyyqsbBnxzCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzCntLessThan(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_CNT <", value, "faZyyqsbBnxzCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzCntLessThanOrEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_CNT <=", value, "faZyyqsbBnxzCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzCntIn(List<Integer> values) {
            addCriterion("FA_ZYYQSB_BNXZ_CNT in", values, "faZyyqsbBnxzCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzCntNotIn(List<Integer> values) {
            addCriterion("FA_ZYYQSB_BNXZ_CNT not in", values, "faZyyqsbBnxzCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzCntBetween(Integer value1, Integer value2) {
            addCriterion("FA_ZYYQSB_BNXZ_CNT between", value1, value2, "faZyyqsbBnxzCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzCntNotBetween(Integer value1, Integer value2) {
            addCriterion("FA_ZYYQSB_BNXZ_CNT not between", value1, value2, "faZyyqsbBnxzCnt");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzJlyqzysbIsNull() {
            addCriterion("FA_ZYYQSB_BNXZ_JLYQZYSB is null");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzJlyqzysbIsNotNull() {
            addCriterion("FA_ZYYQSB_BNXZ_JLYQZYSB is not null");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzJlyqzysbEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_JLYQZYSB =", value, "faZyyqsbBnxzJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzJlyqzysbNotEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_JLYQZYSB <>", value, "faZyyqsbBnxzJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzJlyqzysbGreaterThan(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_JLYQZYSB >", value, "faZyyqsbBnxzJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzJlyqzysbGreaterThanOrEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_JLYQZYSB >=", value, "faZyyqsbBnxzJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzJlyqzysbLessThan(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_JLYQZYSB <", value, "faZyyqsbBnxzJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzJlyqzysbLessThanOrEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_JLYQZYSB <=", value, "faZyyqsbBnxzJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzJlyqzysbIn(List<Integer> values) {
            addCriterion("FA_ZYYQSB_BNXZ_JLYQZYSB in", values, "faZyyqsbBnxzJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzJlyqzysbNotIn(List<Integer> values) {
            addCriterion("FA_ZYYQSB_BNXZ_JLYQZYSB not in", values, "faZyyqsbBnxzJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzJlyqzysbBetween(Integer value1, Integer value2) {
            addCriterion("FA_ZYYQSB_BNXZ_JLYQZYSB between", value1, value2, "faZyyqsbBnxzJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzJlyqzysbNotBetween(Integer value1, Integer value2) {
            addCriterion("FA_ZYYQSB_BNXZ_JLYQZYSB not between", value1, value2, "faZyyqsbBnxzJlyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzTzsbjyyqzysbIsNull() {
            addCriterion("FA_ZYYQSB_BNXZ_TZSBJYYQZYSB is null");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzTzsbjyyqzysbIsNotNull() {
            addCriterion("FA_ZYYQSB_BNXZ_TZSBJYYQZYSB is not null");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzTzsbjyyqzysbEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_TZSBJYYQZYSB =", value, "faZyyqsbBnxzTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzTzsbjyyqzysbNotEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_TZSBJYYQZYSB <>", value, "faZyyqsbBnxzTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzTzsbjyyqzysbGreaterThan(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_TZSBJYYQZYSB >", value, "faZyyqsbBnxzTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzTzsbjyyqzysbGreaterThanOrEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_TZSBJYYQZYSB >=", value, "faZyyqsbBnxzTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzTzsbjyyqzysbLessThan(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_TZSBJYYQZYSB <", value, "faZyyqsbBnxzTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzTzsbjyyqzysbLessThanOrEqualTo(Integer value) {
            addCriterion("FA_ZYYQSB_BNXZ_TZSBJYYQZYSB <=", value, "faZyyqsbBnxzTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzTzsbjyyqzysbIn(List<Integer> values) {
            addCriterion("FA_ZYYQSB_BNXZ_TZSBJYYQZYSB in", values, "faZyyqsbBnxzTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzTzsbjyyqzysbNotIn(List<Integer> values) {
            addCriterion("FA_ZYYQSB_BNXZ_TZSBJYYQZYSB not in", values, "faZyyqsbBnxzTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzTzsbjyyqzysbBetween(Integer value1, Integer value2) {
            addCriterion("FA_ZYYQSB_BNXZ_TZSBJYYQZYSB between", value1, value2, "faZyyqsbBnxzTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaZyyqsbBnxzTzsbjyyqzysbNotBetween(Integer value1, Integer value2) {
            addCriterion("FA_ZYYQSB_BNXZ_TZSBJYYQZYSB not between", value1, value2, "faZyyqsbBnxzTzsbjyyqzysb");
            return (Criteria) this;
        }

        public Criteria andFaOtherIsNull() {
            addCriterion("FA_OTHER is null");
            return (Criteria) this;
        }

        public Criteria andFaOtherIsNotNull() {
            addCriterion("FA_OTHER is not null");
            return (Criteria) this;
        }

        public Criteria andFaOtherEqualTo(Integer value) {
            addCriterion("FA_OTHER =", value, "faOther");
            return (Criteria) this;
        }

        public Criteria andFaOtherNotEqualTo(Integer value) {
            addCriterion("FA_OTHER <>", value, "faOther");
            return (Criteria) this;
        }

        public Criteria andFaOtherGreaterThan(Integer value) {
            addCriterion("FA_OTHER >", value, "faOther");
            return (Criteria) this;
        }

        public Criteria andFaOtherGreaterThanOrEqualTo(Integer value) {
            addCriterion("FA_OTHER >=", value, "faOther");
            return (Criteria) this;
        }

        public Criteria andFaOtherLessThan(Integer value) {
            addCriterion("FA_OTHER <", value, "faOther");
            return (Criteria) this;
        }

        public Criteria andFaOtherLessThanOrEqualTo(Integer value) {
            addCriterion("FA_OTHER <=", value, "faOther");
            return (Criteria) this;
        }

        public Criteria andFaOtherIn(List<Integer> values) {
            addCriterion("FA_OTHER in", values, "faOther");
            return (Criteria) this;
        }

        public Criteria andFaOtherNotIn(List<Integer> values) {
            addCriterion("FA_OTHER not in", values, "faOther");
            return (Criteria) this;
        }

        public Criteria andFaOtherBetween(Integer value1, Integer value2) {
            addCriterion("FA_OTHER between", value1, value2, "faOther");
            return (Criteria) this;
        }

        public Criteria andFaOtherNotBetween(Integer value1, Integer value2) {
            addCriterion("FA_OTHER not between", value1, value2, "faOther");
            return (Criteria) this;
        }

        public Criteria andBCntIsNull() {
            addCriterion("B_CNT is null");
            return (Criteria) this;
        }

        public Criteria andBCntIsNotNull() {
            addCriterion("B_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andBCntEqualTo(Integer value) {
            addCriterion("B_CNT =", value, "bCnt");
            return (Criteria) this;
        }

        public Criteria andBCntNotEqualTo(Integer value) {
            addCriterion("B_CNT <>", value, "bCnt");
            return (Criteria) this;
        }

        public Criteria andBCntGreaterThan(Integer value) {
            addCriterion("B_CNT >", value, "bCnt");
            return (Criteria) this;
        }

        public Criteria andBCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("B_CNT >=", value, "bCnt");
            return (Criteria) this;
        }

        public Criteria andBCntLessThan(Integer value) {
            addCriterion("B_CNT <", value, "bCnt");
            return (Criteria) this;
        }

        public Criteria andBCntLessThanOrEqualTo(Integer value) {
            addCriterion("B_CNT <=", value, "bCnt");
            return (Criteria) this;
        }

        public Criteria andBCntIn(List<Integer> values) {
            addCriterion("B_CNT in", values, "bCnt");
            return (Criteria) this;
        }

        public Criteria andBCntNotIn(List<Integer> values) {
            addCriterion("B_CNT not in", values, "bCnt");
            return (Criteria) this;
        }

        public Criteria andBCntBetween(Integer value1, Integer value2) {
            addCriterion("B_CNT between", value1, value2, "bCnt");
            return (Criteria) this;
        }

        public Criteria andBCntNotBetween(Integer value1, Integer value2) {
            addCriterion("B_CNT not between", value1, value2, "bCnt");
            return (Criteria) this;
        }

        public Criteria andBSysmjCntIsNull() {
            addCriterion("B_SYSMJ_CNT is null");
            return (Criteria) this;
        }

        public Criteria andBSysmjCntIsNotNull() {
            addCriterion("B_SYSMJ_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andBSysmjCntEqualTo(Integer value) {
            addCriterion("B_SYSMJ_CNT =", value, "bSysmjCnt");
            return (Criteria) this;
        }

        public Criteria andBSysmjCntNotEqualTo(Integer value) {
            addCriterion("B_SYSMJ_CNT <>", value, "bSysmjCnt");
            return (Criteria) this;
        }

        public Criteria andBSysmjCntGreaterThan(Integer value) {
            addCriterion("B_SYSMJ_CNT >", value, "bSysmjCnt");
            return (Criteria) this;
        }

        public Criteria andBSysmjCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("B_SYSMJ_CNT >=", value, "bSysmjCnt");
            return (Criteria) this;
        }

        public Criteria andBSysmjCntLessThan(Integer value) {
            addCriterion("B_SYSMJ_CNT <", value, "bSysmjCnt");
            return (Criteria) this;
        }

        public Criteria andBSysmjCntLessThanOrEqualTo(Integer value) {
            addCriterion("B_SYSMJ_CNT <=", value, "bSysmjCnt");
            return (Criteria) this;
        }

        public Criteria andBSysmjCntIn(List<Integer> values) {
            addCriterion("B_SYSMJ_CNT in", values, "bSysmjCnt");
            return (Criteria) this;
        }

        public Criteria andBSysmjCntNotIn(List<Integer> values) {
            addCriterion("B_SYSMJ_CNT not in", values, "bSysmjCnt");
            return (Criteria) this;
        }

        public Criteria andBSysmjCntBetween(Integer value1, Integer value2) {
            addCriterion("B_SYSMJ_CNT between", value1, value2, "bSysmjCnt");
            return (Criteria) this;
        }

        public Criteria andBSysmjCntNotBetween(Integer value1, Integer value2) {
            addCriterion("B_SYSMJ_CNT not between", value1, value2, "bSysmjCnt");
            return (Criteria) this;
        }

        public Criteria andBJysysmjIsNull() {
            addCriterion("B_JYSYSMJ is null");
            return (Criteria) this;
        }

        public Criteria andBJysysmjIsNotNull() {
            addCriterion("B_JYSYSMJ is not null");
            return (Criteria) this;
        }

        public Criteria andBJysysmjEqualTo(Integer value) {
            addCriterion("B_JYSYSMJ =", value, "bJysysmj");
            return (Criteria) this;
        }

        public Criteria andBJysysmjNotEqualTo(Integer value) {
            addCriterion("B_JYSYSMJ <>", value, "bJysysmj");
            return (Criteria) this;
        }

        public Criteria andBJysysmjGreaterThan(Integer value) {
            addCriterion("B_JYSYSMJ >", value, "bJysysmj");
            return (Criteria) this;
        }

        public Criteria andBJysysmjGreaterThanOrEqualTo(Integer value) {
            addCriterion("B_JYSYSMJ >=", value, "bJysysmj");
            return (Criteria) this;
        }

        public Criteria andBJysysmjLessThan(Integer value) {
            addCriterion("B_JYSYSMJ <", value, "bJysysmj");
            return (Criteria) this;
        }

        public Criteria andBJysysmjLessThanOrEqualTo(Integer value) {
            addCriterion("B_JYSYSMJ <=", value, "bJysysmj");
            return (Criteria) this;
        }

        public Criteria andBJysysmjIn(List<Integer> values) {
            addCriterion("B_JYSYSMJ in", values, "bJysysmj");
            return (Criteria) this;
        }

        public Criteria andBJysysmjNotIn(List<Integer> values) {
            addCriterion("B_JYSYSMJ not in", values, "bJysysmj");
            return (Criteria) this;
        }

        public Criteria andBJysysmjBetween(Integer value1, Integer value2) {
            addCriterion("B_JYSYSMJ between", value1, value2, "bJysysmj");
            return (Criteria) this;
        }

        public Criteria andBJysysmjNotBetween(Integer value1, Integer value2) {
            addCriterion("B_JYSYSMJ not between", value1, value2, "bJysysmj");
            return (Criteria) this;
        }

        public Criteria andBTzsbsysmjIsNull() {
            addCriterion("B_TZSBSYSMJ is null");
            return (Criteria) this;
        }

        public Criteria andBTzsbsysmjIsNotNull() {
            addCriterion("B_TZSBSYSMJ is not null");
            return (Criteria) this;
        }

        public Criteria andBTzsbsysmjEqualTo(Integer value) {
            addCriterion("B_TZSBSYSMJ =", value, "bTzsbsysmj");
            return (Criteria) this;
        }

        public Criteria andBTzsbsysmjNotEqualTo(Integer value) {
            addCriterion("B_TZSBSYSMJ <>", value, "bTzsbsysmj");
            return (Criteria) this;
        }

        public Criteria andBTzsbsysmjGreaterThan(Integer value) {
            addCriterion("B_TZSBSYSMJ >", value, "bTzsbsysmj");
            return (Criteria) this;
        }

        public Criteria andBTzsbsysmjGreaterThanOrEqualTo(Integer value) {
            addCriterion("B_TZSBSYSMJ >=", value, "bTzsbsysmj");
            return (Criteria) this;
        }

        public Criteria andBTzsbsysmjLessThan(Integer value) {
            addCriterion("B_TZSBSYSMJ <", value, "bTzsbsysmj");
            return (Criteria) this;
        }

        public Criteria andBTzsbsysmjLessThanOrEqualTo(Integer value) {
            addCriterion("B_TZSBSYSMJ <=", value, "bTzsbsysmj");
            return (Criteria) this;
        }

        public Criteria andBTzsbsysmjIn(List<Integer> values) {
            addCriterion("B_TZSBSYSMJ in", values, "bTzsbsysmj");
            return (Criteria) this;
        }

        public Criteria andBTzsbsysmjNotIn(List<Integer> values) {
            addCriterion("B_TZSBSYSMJ not in", values, "bTzsbsysmj");
            return (Criteria) this;
        }

        public Criteria andBTzsbsysmjBetween(Integer value1, Integer value2) {
            addCriterion("B_TZSBSYSMJ between", value1, value2, "bTzsbsysmj");
            return (Criteria) this;
        }

        public Criteria andBTzsbsysmjNotBetween(Integer value1, Integer value2) {
            addCriterion("B_TZSBSYSMJ not between", value1, value2, "bTzsbsysmj");
            return (Criteria) this;
        }

        public Criteria andBBgyfmjIsNull() {
            addCriterion("B_BGYFMJ is null");
            return (Criteria) this;
        }

        public Criteria andBBgyfmjIsNotNull() {
            addCriterion("B_BGYFMJ is not null");
            return (Criteria) this;
        }

        public Criteria andBBgyfmjEqualTo(Integer value) {
            addCriterion("B_BGYFMJ =", value, "bBgyfmj");
            return (Criteria) this;
        }

        public Criteria andBBgyfmjNotEqualTo(Integer value) {
            addCriterion("B_BGYFMJ <>", value, "bBgyfmj");
            return (Criteria) this;
        }

        public Criteria andBBgyfmjGreaterThan(Integer value) {
            addCriterion("B_BGYFMJ >", value, "bBgyfmj");
            return (Criteria) this;
        }

        public Criteria andBBgyfmjGreaterThanOrEqualTo(Integer value) {
            addCriterion("B_BGYFMJ >=", value, "bBgyfmj");
            return (Criteria) this;
        }

        public Criteria andBBgyfmjLessThan(Integer value) {
            addCriterion("B_BGYFMJ <", value, "bBgyfmj");
            return (Criteria) this;
        }

        public Criteria andBBgyfmjLessThanOrEqualTo(Integer value) {
            addCriterion("B_BGYFMJ <=", value, "bBgyfmj");
            return (Criteria) this;
        }

        public Criteria andBBgyfmjIn(List<Integer> values) {
            addCriterion("B_BGYFMJ in", values, "bBgyfmj");
            return (Criteria) this;
        }

        public Criteria andBBgyfmjNotIn(List<Integer> values) {
            addCriterion("B_BGYFMJ not in", values, "bBgyfmj");
            return (Criteria) this;
        }

        public Criteria andBBgyfmjBetween(Integer value1, Integer value2) {
            addCriterion("B_BGYFMJ between", value1, value2, "bBgyfmj");
            return (Criteria) this;
        }

        public Criteria andBBgyfmjNotBetween(Integer value1, Integer value2) {
            addCriterion("B_BGYFMJ not between", value1, value2, "bBgyfmj");
            return (Criteria) this;
        }

        public Criteria andBOtherIsNull() {
            addCriterion("B_OTHER is null");
            return (Criteria) this;
        }

        public Criteria andBOtherIsNotNull() {
            addCriterion("B_OTHER is not null");
            return (Criteria) this;
        }

        public Criteria andBOtherEqualTo(Integer value) {
            addCriterion("B_OTHER =", value, "bOther");
            return (Criteria) this;
        }

        public Criteria andBOtherNotEqualTo(Integer value) {
            addCriterion("B_OTHER <>", value, "bOther");
            return (Criteria) this;
        }

        public Criteria andBOtherGreaterThan(Integer value) {
            addCriterion("B_OTHER >", value, "bOther");
            return (Criteria) this;
        }

        public Criteria andBOtherGreaterThanOrEqualTo(Integer value) {
            addCriterion("B_OTHER >=", value, "bOther");
            return (Criteria) this;
        }

        public Criteria andBOtherLessThan(Integer value) {
            addCriterion("B_OTHER <", value, "bOther");
            return (Criteria) this;
        }

        public Criteria andBOtherLessThanOrEqualTo(Integer value) {
            addCriterion("B_OTHER <=", value, "bOther");
            return (Criteria) this;
        }

        public Criteria andBOtherIn(List<Integer> values) {
            addCriterion("B_OTHER in", values, "bOther");
            return (Criteria) this;
        }

        public Criteria andBOtherNotIn(List<Integer> values) {
            addCriterion("B_OTHER not in", values, "bOther");
            return (Criteria) this;
        }

        public Criteria andBOtherBetween(Integer value1, Integer value2) {
            addCriterion("B_OTHER between", value1, value2, "bOther");
            return (Criteria) this;
        }

        public Criteria andBOtherNotBetween(Integer value1, Integer value2) {
            addCriterion("B_OTHER not between", value1, value2, "bOther");
            return (Criteria) this;
        }

        public Criteria andCcBnzjxmIsNull() {
            addCriterion("CC_BNZJXM is null");
            return (Criteria) this;
        }

        public Criteria andCcBnzjxmIsNotNull() {
            addCriterion("CC_BNZJXM is not null");
            return (Criteria) this;
        }

        public Criteria andCcBnzjxmEqualTo(Integer value) {
            addCriterion("CC_BNZJXM =", value, "ccBnzjxm");
            return (Criteria) this;
        }

        public Criteria andCcBnzjxmNotEqualTo(Integer value) {
            addCriterion("CC_BNZJXM <>", value, "ccBnzjxm");
            return (Criteria) this;
        }

        public Criteria andCcBnzjxmGreaterThan(Integer value) {
            addCriterion("CC_BNZJXM >", value, "ccBnzjxm");
            return (Criteria) this;
        }

        public Criteria andCcBnzjxmGreaterThanOrEqualTo(Integer value) {
            addCriterion("CC_BNZJXM >=", value, "ccBnzjxm");
            return (Criteria) this;
        }

        public Criteria andCcBnzjxmLessThan(Integer value) {
            addCriterion("CC_BNZJXM <", value, "ccBnzjxm");
            return (Criteria) this;
        }

        public Criteria andCcBnzjxmLessThanOrEqualTo(Integer value) {
            addCriterion("CC_BNZJXM <=", value, "ccBnzjxm");
            return (Criteria) this;
        }

        public Criteria andCcBnzjxmIn(List<Integer> values) {
            addCriterion("CC_BNZJXM in", values, "ccBnzjxm");
            return (Criteria) this;
        }

        public Criteria andCcBnzjxmNotIn(List<Integer> values) {
            addCriterion("CC_BNZJXM not in", values, "ccBnzjxm");
            return (Criteria) this;
        }

        public Criteria andCcBnzjxmBetween(Integer value1, Integer value2) {
            addCriterion("CC_BNZJXM between", value1, value2, "ccBnzjxm");
            return (Criteria) this;
        }

        public Criteria andCcBnzjxmNotBetween(Integer value1, Integer value2) {
            addCriterion("CC_BNZJXM not between", value1, value2, "ccBnzjxm");
            return (Criteria) this;
        }

        public Criteria andCcBntzjeIsNull() {
            addCriterion("CC_BNTZJE is null");
            return (Criteria) this;
        }

        public Criteria andCcBntzjeIsNotNull() {
            addCriterion("CC_BNTZJE is not null");
            return (Criteria) this;
        }

        public Criteria andCcBntzjeEqualTo(Integer value) {
            addCriterion("CC_BNTZJE =", value, "ccBntzje");
            return (Criteria) this;
        }

        public Criteria andCcBntzjeNotEqualTo(Integer value) {
            addCriterion("CC_BNTZJE <>", value, "ccBntzje");
            return (Criteria) this;
        }

        public Criteria andCcBntzjeGreaterThan(Integer value) {
            addCriterion("CC_BNTZJE >", value, "ccBntzje");
            return (Criteria) this;
        }

        public Criteria andCcBntzjeGreaterThanOrEqualTo(Integer value) {
            addCriterion("CC_BNTZJE >=", value, "ccBntzje");
            return (Criteria) this;
        }

        public Criteria andCcBntzjeLessThan(Integer value) {
            addCriterion("CC_BNTZJE <", value, "ccBntzje");
            return (Criteria) this;
        }

        public Criteria andCcBntzjeLessThanOrEqualTo(Integer value) {
            addCriterion("CC_BNTZJE <=", value, "ccBntzje");
            return (Criteria) this;
        }

        public Criteria andCcBntzjeIn(List<Integer> values) {
            addCriterion("CC_BNTZJE in", values, "ccBntzje");
            return (Criteria) this;
        }

        public Criteria andCcBntzjeNotIn(List<Integer> values) {
            addCriterion("CC_BNTZJE not in", values, "ccBntzje");
            return (Criteria) this;
        }

        public Criteria andCcBntzjeBetween(Integer value1, Integer value2) {
            addCriterion("CC_BNTZJE between", value1, value2, "ccBntzje");
            return (Criteria) this;
        }

        public Criteria andCcBntzjeNotBetween(Integer value1, Integer value2) {
            addCriterion("CC_BNTZJE not between", value1, value2, "ccBntzje");
            return (Criteria) this;
        }

        public Criteria andCcBnzjjzmjIsNull() {
            addCriterion("CC_BNZJJZMJ is null");
            return (Criteria) this;
        }

        public Criteria andCcBnzjjzmjIsNotNull() {
            addCriterion("CC_BNZJJZMJ is not null");
            return (Criteria) this;
        }

        public Criteria andCcBnzjjzmjEqualTo(Integer value) {
            addCriterion("CC_BNZJJZMJ =", value, "ccBnzjjzmj");
            return (Criteria) this;
        }

        public Criteria andCcBnzjjzmjNotEqualTo(Integer value) {
            addCriterion("CC_BNZJJZMJ <>", value, "ccBnzjjzmj");
            return (Criteria) this;
        }

        public Criteria andCcBnzjjzmjGreaterThan(Integer value) {
            addCriterion("CC_BNZJJZMJ >", value, "ccBnzjjzmj");
            return (Criteria) this;
        }

        public Criteria andCcBnzjjzmjGreaterThanOrEqualTo(Integer value) {
            addCriterion("CC_BNZJJZMJ >=", value, "ccBnzjjzmj");
            return (Criteria) this;
        }

        public Criteria andCcBnzjjzmjLessThan(Integer value) {
            addCriterion("CC_BNZJJZMJ <", value, "ccBnzjjzmj");
            return (Criteria) this;
        }

        public Criteria andCcBnzjjzmjLessThanOrEqualTo(Integer value) {
            addCriterion("CC_BNZJJZMJ <=", value, "ccBnzjjzmj");
            return (Criteria) this;
        }

        public Criteria andCcBnzjjzmjIn(List<Integer> values) {
            addCriterion("CC_BNZJJZMJ in", values, "ccBnzjjzmj");
            return (Criteria) this;
        }

        public Criteria andCcBnzjjzmjNotIn(List<Integer> values) {
            addCriterion("CC_BNZJJZMJ not in", values, "ccBnzjjzmj");
            return (Criteria) this;
        }

        public Criteria andCcBnzjjzmjBetween(Integer value1, Integer value2) {
            addCriterion("CC_BNZJJZMJ between", value1, value2, "ccBnzjjzmj");
            return (Criteria) this;
        }

        public Criteria andCcBnzjjzmjNotBetween(Integer value1, Integer value2) {
            addCriterion("CC_BNZJJZMJ not between", value1, value2, "ccBnzjjzmj");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("YEAR is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(Integer value) {
            addCriterion("YEAR =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(Integer value) {
            addCriterion("YEAR <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(Integer value) {
            addCriterion("YEAR >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("YEAR >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(Integer value) {
            addCriterion("YEAR <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(Integer value) {
            addCriterion("YEAR <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<Integer> values) {
            addCriterion("YEAR in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<Integer> values) {
            addCriterion("YEAR not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(Integer value1, Integer value2) {
            addCriterion("YEAR between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(Integer value1, Integer value2) {
            addCriterion("YEAR not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("PROVINCE is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("PROVINCE is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("PROVINCE =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("PROVINCE <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("PROVINCE >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("PROVINCE >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("PROVINCE <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("PROVINCE <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("PROVINCE like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("PROVINCE not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("PROVINCE in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("PROVINCE not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("PROVINCE between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("PROVINCE not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andSeqnoIsNull() {
            addCriterion("SEQNO is null");
            return (Criteria) this;
        }

        public Criteria andSeqnoIsNotNull() {
            addCriterion("SEQNO is not null");
            return (Criteria) this;
        }

        public Criteria andSeqnoEqualTo(Integer value) {
            addCriterion("SEQNO =", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotEqualTo(Integer value) {
            addCriterion("SEQNO <>", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoGreaterThan(Integer value) {
            addCriterion("SEQNO >", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("SEQNO >=", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLessThan(Integer value) {
            addCriterion("SEQNO <", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLessThanOrEqualTo(Integer value) {
            addCriterion("SEQNO <=", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoIn(List<Integer> values) {
            addCriterion("SEQNO in", values, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotIn(List<Integer> values) {
            addCriterion("SEQNO not in", values, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoBetween(Integer value1, Integer value2) {
            addCriterion("SEQNO between", value1, value2, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotBetween(Integer value1, Integer value2) {
            addCriterion("SEQNO not between", value1, value2, "seqno");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 25 19:38:15 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fixedassetsandcapitalconstruction
     *
     * @mbggenerated Wed Jul 25 19:38:15 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}